### ISSUE TITLE
Dodger demo by B.U.D.D not working on U64

### ISSUE THREAD

**Issue by mlund** [GideonZ/1541ultimate#106]
Running [Dodger.d64](https://csdb.dk/release/download.php?id=221933) the demo unpacks, but then returns to blue "Ready" prompt before starting. I use U64 v1.21 - 3.5a; cartridge is set to None; and "Run disk" from the menu. I hope this is the right place to post this?

**Comment by Grrrolf** [comment]
The first part of this demo doesn't work on a real c64 either. So, I guess this is expected behaviour?
Load the second part and watch the demo from there on.

**Comment by mlund** [comment]
Thanks for checking. I confirm identical behavior with vice emulating various c64 revisions and drives.

**Comment by mlund** [comment]
For reference, the d64 file on csdb.org seems corrupted, but the following creates a new disk file that runs fine on both U64 and vice:
~~~ bash
wget http://www.zimmers.net/anonftp/pub/cbm/c64/demos/pal/Nato/Dodger.lnx
cbmconvert -D4 dodger.d64 -l Dodger.lnx # http://www.zimmers.net/anonftp/pub/cbm/crossplatform/converters/unix/index.html
~~~
