### ISSUE TITLE
[Ultimate2+ firmware 3.4c] audio channel left/right have been reversed

### ISSUE THREAD

**Issue by Grrrolf** [GideonZ/1541ultimate#107]
For a while (probably since the audio mixer has been implemented) the left and right channel have been reversed. In essence when panning all audio to the left channel, it outputs the audio on the right channel. When panning all the audio to the right channel, it outputs the audio on the left channel. 

This probably also concerns the U2, but I can't check since someone else has my U2 in use.

I have mentioned this on facebook when I discovered this, but never did a follow up on it (hence, filing an issue here).

**Comment by GideonZ** [comment]
Fixed in 1.26 and later.
