### ISSUE TITLE
Soft IEC seq file reading issue with GET#

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#109]
I created a seq file by opening, printing, closing. But reading it back gives a wrong every 2nd character.

![20190922_114827](https://user-images.githubusercontent.com/1909642/65391474-32faa800-dd2f-11e9-91c1-88910defc5ab.jpg)

Ultimate 64 v1.22 3.5b

**Comment by xlar54** [comment]
i found this while working on my code. it seems there is a second thread happening for each subsequent character prefetch.

**Comment by xlar54** [comment]
This code in my 1581 branch seems to fix the issue.  Havent tested with the soft IEC, but will:
not 100% certain of why it works - took lots of hours and trial and error, but it works perfectly fine on the 81 branch.  This would go into /software/io/iec/iec_channel.cc

`int IecChannel :: prefetch_data(uint8_t& data)
{
    if (state == e_error) {
        return IEC_NO_FILE;
    }
    if (pointer == last_byte) {
        data = buffer[prefetch];
        pointer = 0;
        prefetch = 0;
        return IEC_LAST;
    }
    if (prefetch < prefetch_max) {
		data = buffer[prefetch];
		prefetch++;
		return IEC_OK;
    }
    if (prefetch > prefetch_max) {
        return IEC_NO_FILE;
    }
    if (prefetch == last_byte)
    {
    	if(channel != 15)
    	{
    		prefetch = pointer;
    		return IEC_OK;
    	}
    	data = buffer[prefetch];
    	return IEC_LAST;
	}

    return IEC_BUFFER_END;
}`

**Comment by xlar54** [comment]
Unfortunately the fix above creates other problems in loading some files, so I have to retract that fix.  But there is something very odd happening when trying to either read the end of a seq file, or if the file is small, the entire thing is wrong.  It definitely has something to do with the pointer and the prefetch values though, and when the pop() vs prefetch_data() functions are called.  What is really strange is that if stepped through in the debugger, it doesnt happen.  Only when breakpoints are removed does it happen.

**Comment by xlar54** [comment]
Ok, here's a working fix.  (Dont know why it gets out of sync, but this fixes it in both the main branch and in my 1581 branch):

int IecChannel :: pop_data(void)
{
    switch(state) {
        case e_file:
            if(pointer == last_byte) {
                state = e_complete;
                return IEC_NO_FILE; // no more data?
            } else if(pointer == 255) {
                if(read_block())  // also resets pointer.
                    return IEC_READ_ERROR;
                else
                    return IEC_OK;
            }
            // temp fix to correct seq read bug
            **if(prefetch > last_byte)
			{
				prefetch = pointer+1;
			}**
            break;

**Comment by GideonZ** [comment]
I think we need to turn on the debug printf statements in the IEC communication itself, to understand what the sequence is of control bytes that we get from the hardware. If I recall correctly, there is a prefetch and a pop; the prefetch is there to get the data to write it to the hardware and the pop is called when the byte is actually acknowledged by the IEC bus. Now that I think of it, it is a rather clumsy way of doing this, as it would have been sufficient to have a fifo with a peek function. Maybe there is more to it, but this clearly needs to be refactored.

**Comment by GideonZ** [comment]
Moved prefetch_reset to the talk command where it belongs.
Also implemented and verified for the command channel, which now also supports GET#
Fixed.
