### ISSUE TITLE
Issue + Feature: Pause Tape function

### ISSUE THREAD

**Issue by RichardTND** [GideonZ/1541ultimate#118]
When playing some games that require the tape to be paused, before loading in the next level (i.e. The Temple of Apshai Trilogy). Pause Tape playback doesn't appear in FREEZE mode when pressing F5, but in the HDMI user interface menu the option can be seen.

Also a feature request (if possible) where pressing F3 can display all of the D64 functions, and F7 can display all of the TAP related functions. F5 for general functions. This would make navigation a lot easier, if playing games on disk, or tape instead of going through a big list of options.

For example:

F3 - Disk Options
Create D64 / Blank Disk
Create G64 / Blank Disk
Ulticopy 8
Ulticopy 9
Reset 1541 Drive A 
Reset 1541 Drive B (If enabled)

F5-General options (as usual)

F7-Tape options

Sample Tape to TAP
Capture Save to TAP
Pause Tape Playback (If running)
Resume Tape Playback (If paused)

**Comment by GideonZ** [comment]
Dear Richard,

It is strange that the Pause Tape playback is seen in freeze but not in hdmi overlay. I will look into this.

Please note that F3 is already the help key, and F7 is "page down", so these keys already have a meaning and use.

What I am planning to do is re-organize the F5 menu and add one level of hierarchy. This is a more future-proof solution than to assign keys to specific functions. The file browser is rather agnostic as to what it is displaying, i.e. it does not know about the tape handler or other disk options. I would like to avoid introducing dependencies. The browser should also compile if there is no tape or disk actions at all.

**Comment by RichardTND** [comment]
It's the other way round :) Pause on HDMI popup but in Freeze when I press F5 I cannot find Pause tape playback :)

**Comment by RichardTND** [comment]
Tape options in freeze menu - Fixed in U64 V3.7.
