### ISSUE TITLE
Invalid default network host name for the Ultimate 64

### ISSUE THREAD

**Issue by Grrrolf** [GideonZ/1541ultimate#119]
After installing the new firmware for the Ultimate 64, I noticed that after a 'reset config' the default network host name has been changed to: "Ultimate 64"

According to [RFC-952](https://tools.ietf.org/html/rfc952):

> A "name" (Net, Host, Gateway, or Domain name) is a text string up to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus sign (-), and period (.).  Note that periods are only allowed when they serve to delimit components of "domain style names". (See RFC-921, "Domain Name System Implementation Schedule", for background).  _**No blank or space characters are permitted as part of a name.**_ No distinction is made between upper and lower case.  The first character must be an alpha character.  The last character must not be a minus sign or period. [...]

It says that spaces are not allowed in host names, meaning that the default host name for the Ultimate 64 is invalid.

**Comment by GideonZ** [comment]
OK!

**Comment by GideonZ** [comment]
Fixed. Will appear corrected in 3.7. Also, illegal input is corrected.
