### ISSUE TITLE
1541-C ROM issues

### ISSUE THREAD

**Issue by micv2** [GideonZ/1541ultimate#121]
Hello, I have the 1541UII. I noticed that from version 3.3 the "1541-C ROM" is not working properly. I was able to start everything without problems with the 1541-C ROM earlier. Today I can not load a demo like "Deus ex Machina" properly, it stops at "Big Breadbox .." screen. With firmware version 3.2 it was still ok. Also other programs are badly loaded. Meanwhile, I have the latest firmware v3.6 Installed, unfortunately without success. Is the 1541-C ROM damaged? Everything is OK with 1541-II ROM. Sorry for my English. Best regards, MiC

**Comment by GideonZ** [comment]
Hi MiC,

It turns out that the 1541C requires the Track 0 sensor input. The Track 0 sensor was disconnected due to the attachment of the parallel cable option (for the U64), which uses Port A of VIA1 in the 1541. So does the track 0 sensor, which is connected to PA0 of VIA1. I am not sure this is the ONLY issue, but I am currently building a test version to verify this.

Gideon

**Comment by GideonZ** [comment]
I can confirm that with track 0 sensor attached, the 1541C ROM seems to work correctly. More thorough testing is required. I will connect the track 0 sensor when the parallel cable is disabled on the U64, and connect it by default on the U2+ for both drives.

**Comment by micv2** [comment]
Hello Gideon, 
thank you for your effort.  The 1541C-ROM has always been my favorite.  Looking forward to an improved firmware for the 1541-UII :).

Have a nice day, 
Paul

Von meinem Handy gesendet

> Am 24.03.2020 um 13:24 schrieb Gideon <notifications@github.com>:
> 
> I can confirm that with track 0 sensor attached, the 1541C ROM seems to work correctly. More thorough testing is required. I will connect the track 0 sensor when the parallel cable is disabled on the U64, and connect it by default on the U2+ for both drives.

**Comment by GideonZ** [comment]
Okay.. not sure if U2 can still build with the current firmware
improvements. I might need to delete some modules from the build to make it
fit. I plan to reorganize the code a lot, to make it more concise and thus
smaller. But this will not happen for 3.7 yet. Therefore, I think that 3.7
will be crippled for the U2, or not exist. U2+ yes and U64 as well.

**Comment by micv2** [comment]
I know Gideon, the 15412+ and U64 are current.  But don't forget the 1541U2 is very common .. if I also think of my friends .. they all have the 1541U2.  Therefore a fix for the 1541U2 would not be bad ;)

Von meinem Handy gesendet

**Comment by GideonZ** [comment]
I could, for instance, remove the printer emulation routines for the U2...
Not pretty, but well, as a temporary solution?

**Comment by micv2** [comment]
Don't stress, we can wait and use 1541-II ROM for so long.  You can fix that later.  I never tried the printer emulation, I don't know if the others are using it .. Not that the others complain :)

Von meinem Handy gesendet

> Am 24.03.2020 um 15:01 schrieb Gideon <notifications@github.com>:
> 
> I could, for instance, remove the printer emulation routines for the U2...
> Not pretty, but well, as a temporary solution?

**Comment by GideonZ** [comment]
I am able to build it, using a slower optimization setting for the PNG
creator module (lodepng). This saves roughly 40 KB of code space. (The U2
is quite code size limited...)
This 40K is plenty to add the ACIA driver and modem emulation layer that
3.7 has. Of course, I'd have to build a single drive FPGA variant with 6551
emulation. I'll try later today to add this option.

**Comment by micv2** [comment]
Great work, I'm happy that the U2 firmware support is not yet dead.  That also speaks for the high quality. Thank you.

Von meinem Handy gesendet

> Am 24.03.2020 um 15:17 schrieb Gideon <notifications@github.com>:
> 
> I am able to build it, using a slower optimization setting for the PNG
> creator module (lodepng). This saves roughly 40 KB of code space. (The U2
> is quite code size limited...)
> This 40K is plenty to add the ACIA driver and modem emulation layer that
> 3.7 has. Of course, I'd have to build a single drive FPGA variant with 6551
> emulation. I'll try later today to add this option.

**Comment by uffejakobsen** [comment]
> I could, for instance, remove the printer emulation routines for the U2... Not pretty, but well, as a temporary solution?

Just my vote for this approach - I've never used the printer emulation :+1:

**Comment by micv2** [comment]
I always use the firmware with 1 drive and sound emu.  Not the one with two drives ..

Von meinem Handy gesendet

> Am 24.03.2020 um 15:36 schrieb Uffe Jakobsen <notifications@github.com>:
> 
> I could, for instance, remove the printer emulation routines for the U2... Not pretty, but well, as a temporary solution?
> 
> Just my vote for this approach - I've never used the printer emulation 👍

**Comment by micv2** [comment]
A stupid question, printer emu for Commodore printers or PC printers?  I have not dealt with it .. PC printer would be cool :)

Von meinem Handy gesendet
