### ISSUE TITLE
ARM2SID FM not playing FM on FW > 1.22

### ISSUE THREAD

**Issue by berrydejager** [GideonZ/1541ultimate#124]
When using the FW 1.22 on a 1.3 Elite board the FM is playing correct (SID1=$D400, SID2=$DF00) while running [FM-YAM Demo Casu Quo by Xentax](https://csdb.dk/release/?id=160488).

Upgrading to FW >1.22 prevents the FM synthesis from playing sounds.

Hardware used:
U64 Elite v1.3
[ARM2SID +FM](https://www.retrocomp.cz/produkt?id=20)

**Comment by GideonZ** [comment]
Does this also apply to 1.26?

**Comment by berrydejager** [comment]
Yes, the 1.26 has the same not-playing-FM-behaviour. Also confirmed here: https://m.facebook.com/groups/378328707752?view=permalink&id=10156684368212753&ref=group_header

**Comment by chrisblown** [comment]
Yes, I'm experiencing the same problem on 1.26 on my U64 (v1.2a) with ARM2SID +FM

**Comment by GideonZ** [comment]
I ordered an ARM2SID+FM and got a confirmation that it is on its way. Once
I received it, I will investigate it further.

**Comment by berrydejager** [comment]
When defining  the second sid at $DF40, the FM works again, also with the new 1.26 firmware.

Case closed!

**Comment by GideonZ** [comment]
Cool.. These are the best kinds of problems, that are solved all by themselves. I still would need to know why it worked on 1.22, while the address range was set to $DF00 ONLY. Maybe it was a bug in 1.22 that made it work?

**Comment by berrydejager** [comment]
More info on the YM3812 and its $DF40 addressing: http://c64.xentax.com/index.php/15-testing-ym3812-register-write-timing

**Comment by markusC64** [comment]
An educated guess: The mentioned settings from firmware 1.22 sounds like "no mirroing, only the given address (size $20).
And with newer firmware, automirroring might be turned on (not mentioned), and setting the 2nd sid to $df40 makes automirroring not to include $df40 for the first sid.

**Comment by chrisblown** [comment]
Thx I'll try it out.. though I swear I tried various addresses with mirror off and on..  If you don't mind what are your exact settings?

**Comment by GideonZ** [comment]
I know that mirroring only works in the D400-D7FF range. However, setting
the external address line to A5, mirroring on $20 will be turned on.
In other words, if DF40 is selected, and A5 is set as external address
split, DF60 is enabled as well. According to the link, DF60 is used for
status readback.

So, the setting should be:  DF40 + Split on A5.

Gideon

**Comment by chrisblown** [comment]
Confirmed $DF40 working here too. Although the YM feature isn't detected it works.

**Comment by GideonZ** [comment]
If it is not detected, you probably have not set the Split on A5, as
mentioned before. This enables the range DF60-DF7F, which is required for
reading the status register.

**Comment by SquireOfGothos** [comment]
Just to clarify there is another setting under 'C64 and Cartridge Settings called Map Ultimate Audio $DF20-DFFF' that needs to be disabled for FM to work.
