### ISSUE TITLE
Builtin FC3 monitor hangs from freezer

### ISSUE THREAD

**Issue by paaco** [GideonZ/1541ultimate#132]
When using the builtin FC3 cartridge (DEC 1988), pressing Restore+button will freeze the C64 and start the FC3 freezer. Choosing "MONITOR" with F7 on the "EXIT" menu is supposed to start the built in monitor. However, only the screen turns blue+lightblue and the C64 hangs.
Going into the U64 menu with F5 and "Reboot C64" will bring it back again.

Using an external FC3 cartridge (SEP 1987) however works fine.

I'm using an U64 Elite (prototype) with software 1.28 - 3.7
Cartridge settings: Final Cart III, Preference Auto, Mode Unchanged, Fast Reset Disabled.

**Comment by t-h-e-joker** [comment]
I can confirm that. The reason is the used ROM (/1541ultimate/roms/final3.bin).
If you use one of the attached CRTs as a "custom CRT", the MON will work.

@gideon
In my opinion you should include the original ROM "1988-12.bin", which starts in the desktop and after that remove this problematic setting "Final Cartridge 3 Mode".

If you hold the "RUN / STOP" button when switching on, you start immediately in FC3-Basic. (original feeling!). Alternatively, the attached FC3 basic start ROM "*1988-13.bin" can be integrated as a custom CRT at any time.

[fc3roms.zip](https://github.com/GideonZ/1541ultimate/files/4579497/fc3roms.zip)

**Comment by markusC64** [comment]
You are sure that the setting "Final Cartridge 3 Mode" causes problems? It's implementation is generic, it is supposed to be able to patch the ROMs you provided as well.

Anyway, I think we should just test the ROM you mentioned without removing that menu setting. BTW: The very first choice of that setting is providing the ROM without any automatic patching for turning desktop on or off. So testing the effect of removing it or not can be tested without removing it. Just a replacement of the ROM in the formware needs to be done.

**Comment by GideonZ** [comment]
In one of the next firmware versions, all carts will be removed, including
the patchwork for FC3.

**Comment by markusC64** [comment]
I can confirm that just replacing the ROM in the firmware solves that problem.

**Comment by paaco** [comment]
As far as I tested the FC3 mode setting did not make any difference (other than correctly ending up in Basic or Desktop). I will check the zip file.

@GideonZ @markusC64 I know this is not really the right place but I since I have your attention ;-) just had a chance to pull my original SID and insert it in my U64E prototype. It's detected in the config menu as 6581 and siddetector.prg also detects it correctly. However I have no sound, not in the builtin player and not in any games or demos. It does still work in my original board. I tried 470 pF setting On/Off and played with the mixer settings to no avail. I unmapped the UltiSid and set socket 1 to $D400. I am using the video out not HDMI. UltiSid works nicely.
Any more suggestions?

**Comment by markusC64** [comment]
Have you checked the mixer having a nonzero volume for Socket 1?

**Comment by paaco** [comment]
Yeah I've tried a couple of things. After a factory reset it appears to work now.
However, it ONLY works when I mount a .d64. If I run a .prg directly from the USB drive, there is no audible sound from the SID. The same goes for "Run Disk" (which takes ages because it doesn't use the FC3 fastloader).

**Comment by GideonZ** [comment]
Reverted to (not-REU-compatible) official version.
