### ISSUE TITLE
Main character sprite in Kongo Kong missing in V1.28 - 3.7

### ISSUE THREAD

**Issue by VinnyMainolfi** [GideonZ/1541ultimate#133]
As discussed, the main character sprite in Kongo Kong is missing during gameplay in V1.28 - 3.7 of Ultimate 64,
[KONGOKON.zip](https://github.com/GideonZ/1541ultimate/files/4533764/KONGOKON.zip)

**Comment by t-h-e-joker** [comment]
If you mean the demonstration mode <F7>, then this also happens on the real C64!
If you start with <F1>, the game on the U64 works just like on the real C64!

**Comment by VinnyMainolfi** [comment]
> If you mean the demonstration mode F7, then this also happens on the real C64!
> If you start with F1, the game on the U64 works just like on the real C64!

No ... the actual game. Don't worry... I was chatting with Gideon last night about it and I showed him a video of the bug.

**Comment by VinnyMainolfi** [comment]
Ah - well spotted! I NEVER knew that!

Thank you for spotting and sorting it. Greatly appreciated :-)))
