### ISSUE TITLE
Timing for Nordic Power

### ISSUE THREAD

**Issue by cmc1976scs** [GideonZ/1541ultimate#135]
Hello,
Is it possible to adjust the timing for the NordicPower as well as for the old action replay MK5 modules? Because the SMD board version works.

thanks

Stefan

**Comment by GideonZ** [comment]
Please clarify which timing parameter needs to change, or why it is failing
currently.

**Comment by markusC64** [comment]
@GideonZ: I do not expect "Nordic Power" alias "Action Power" to work. I think I'll work on it tommorrow.
With Action Replay, I am not aware of any problems.

**Comment by markusC64** [comment]
@GideonZ: I think I've found why "Nodic Power" is not working. It has nothing to do with timing.

You'll get a merge request soon.

**Comment by cmc1976scs** [comment]
Hi,

I have now tested it with a real hardware, so the module does not work. Then I took a .crt file from Noric Power, which works if you just mount it. If I flash it as custom CRT and then restart it, I have a black screen. 
When I plug in my Action Replay MK6 (SMD board) I get back to the settings in the U64 and can deactivate the custom rom so that the U64E starts again.
I hope my info helps you!
Otherwise, maybe someone can write to me in german and I can explain it even better!

**Comment by markusC64** [comment]
Hm, loading crt automatically enables bus mode 'write' at least. Having the crt flashed may not do so., Can you try setting bus mode to 'write' and check if that resolves that problem.

I'll do a deeper check if that advice does not help.

**Comment by GideonZ** [comment]
This might indeed be the problem. THe code for loading cartridges is kind
of messy at the moment, and needs refactoring.
It's on my todo list to remove all internal cart binaries and simply use
CRT files only.

**Comment by cmc1976scs** [comment]
But then it would be good if you could give the crt files names!  So not only Customer!  What.  I wonder why the action Replay MK6 last version with PLCC Eeprom is about expansion port.  All other modules built in DIL logic do not work?



Stefan Kauf
Waldstraße 15<x-apple-data-detectors://9/1>
65719 Hofheim<x-apple-data-detectors://9/1>

Mobil: +49 179 1157760<tel:+49%20179%201157760>
s.kauf@edv-Kauf.de<mailto:s.kauf@edv-Kauf.de>



USt.-Id-Nr.: DE260264223

This e-mail message may contain confidential or privileged information. If you are not the intended recipient, please delete the message and any attachments and notify the sender by return e-mail. You should not retain, distribute, disclose, or use any of the information on this message

Am 15.06.2020 um 19:38 schrieb Gideon <notifications@github.com>:

﻿

This might indeed be the problem. THe code for loading cartridges is kind
of messy at the moment, and needs refactoring.
It's on my todo list to remove all internal cart binaries and simply use
CRT files only.

**Comment by markusC64** [comment]
I am testing that myself. Please avoid under all circumstances the above combination together with cartridge mode "internal". There is a grave bug in that combination.

If cartridge mode is 'auto', you can help yourself by inserting a cartridge - that seems to be ok for testing.

**Comment by cmc1976scs** [comment]
In the Monet I use my external MK6 (SMD version) which worked from the beginning!



If I can help in any way, just give a short info.



Otherwise it's already a good thing the U64E!


Stefan Kauf
Waldstraße 15<x-apple-data-detectors://9/1>
65719 Hofheim<x-apple-data-detectors://9/1>

Mobil: +49 179 1157760<tel:+49%20179%201157760>
s.kauf@edv-Kauf.de<mailto:s.kauf@edv-Kauf.de>



USt.-Id-Nr.: DE260264223

This e-mail message may contain confidential or privileged information. If you are not the intended recipient, please delete the message and any attachments and notify the sender by return e-mail. You should not retain, distribute, disclose, or use any of the information on this message

Am 15.06.2020 um 20:12 schrieb markusC64 <notifications@github.com>:


I am testing that myself. Please avoid under all circumstances the above combination together with cartridge mode "internal". There is a grave bug in that combination.

If cartridge mode is 'auto', you can help yourself by inserting a cartridge - that seems to be ok for testing

**Comment by cmc1976scs** [comment]
This board version of the Aktion Replay MK6 goes to the U64E.  Here is a picture of the board.

[cid:544FD378-E09C-4525-8724-AE8B0DBFF715]


Stefan Kauf
Waldstraße 15<x-apple-data-detectors://9/1>
65719 Hofheim<x-apple-data-detectors://9/1>

Mobil: +49 179 1157760<tel:+49%20179%201157760>
s.kauf@edv-Kauf.de<mailto:s.kauf@edv-Kauf.de>



USt.-Id-Nr.: DE260264223

This e-mail message may contain confidential or privileged information. If you are not the intended recipient, please delete the message and any attachments and notify the sender by return e-mail. You should not retain, distribute, disclose, or use any of the information on this message

Am 15.06.2020 um 20:12 schrieb markusC64 <notifications@github.com>:

﻿

I am testing that myself. Please avoid under all circumstances the above combination together with cartridge mode "internal". There is a grave bug in that combination.

If cartridge mode is 'auto', you can help yourself by inserting a cartridge - that seems to be ok for testing.

**Comment by cmc1976scs** [comment]
Hi, so I tested it now that flashing works and the U64E also boots afterwards!
Thanks again...

**Comment by GideonZ** [comment]
@cmc1976scs So this means that this issue can be closed?

**Comment by cmc1976scs** [comment]
Actually what would be nice if the old boards from the action replay like Nordic etc.. would run. I haven't been able to test if the original modules work. the crts will definitely work!


Von: Gideon <notifications@github.com>
Gesendet: Montag, 22. Juni 2020 18:59
An: GideonZ/1541ultimate <1541ultimate@noreply.github.com>
Cc: Stefan Kauf <s.kauf@edv-kauf.de>; Mention <mention@noreply.github.com>
Betreff: Re: [GideonZ/1541ultimate] Timing for Nordic Power (#135)


@cmc1976scs<https://github.com/cmc1976scs> So this means that this issue can be closed?

**Comment by markusC64** [comment]
Perhaps we could close this and open another issue for problems with real cartridges on expansion port. Emulation incompatibilities and problems with real cartridges are somehow different.

For supporting Action Replay < 4.2 (i. e. MK1, MK2, MK3 and MK4, information is needed. These modules are either buggy or they do not work corrently in VICE, so VICE cannot be used as a reference).

For Atomic power alias nordic power, AFAIK all available ROMs are working.
