### ISSUE TITLE
Feature Request: Alternate Page Sizes for Virtual Printer

### ISSUE THREAD

**Issue by rlipenta** [GideonZ/1541ultimate#137]
It would be great if we could have the ability to use US Letter size "paper" with the virtual printer.

**Comment by rgc2000** [comment]
Is it really needed? You have a png file that you can print on a real printer. You have margins around the printable area that the virtual printer will never allow you to print on. If scaled to 100% the printable area is 8x10 inches (20.32x25.4 cm). It fits in both A4 and US Letter.

**Comment by GideonZ** [comment]
I think Rene's answer is sufficient. :+1:
