### ISSUE TITLE
Data loss on eject if save fails

### ISSUE THREAD

**Issue by RefriedNoodleNL** [GideonZ/1541ultimate#147]
I noticed the following behaviour: (Ultimate64 Elite, v1.29)
- Insert a blank disk in the virtual 1541,
- Write to the disk,
- Eject the disk
- U64 asks if you want to save it before ejecting. When answering 'yes', it asks for a filename.
- If the save fails for whatever reason (file already exists, or filesystem is not writable), the disk gets ejected anyway, meaning the data is lost.

I'd recommend that if the save fails, the disk does not get ejected.

**Comment by GideonZ** [comment]
Implemented extra dialogs.
