### ISSUE TITLE
U64E hangs with black screen after update 1.33

### ISSUE THREAD

**Issue by paaco** [GideonZ/1541ultimate#156]
To verify issue #132 I flashed the new 1.33 but now the screen (S-Video) stays black.
I did not reset my configuration.
I noticed that you pulled the firmware because of a possible bootloop.

Is there a recovery procedure to go back to 1.26?

I tried putting the content of u64_recovery_1.22.zip onto a flash drive but that did not do the trick.

**Comment by marty41** [comment]
Did you try to hook the board to a HDMI/DVI display to see if it is still running?
You could also try to telnet to the board and reset your configuration.

**Comment by markusC64** [comment]
Depending on the settings of the Ultimate 64, insertinmg a external cartidge might also help.

**Comment by paaco** [comment]
@markusC64 Thanks, inserting an FC3 made the U64 boot properly again.

@GideonZ Is there some configuration to fix (factory reset?) or should I just wait for a new version?

**Comment by GideonZ** [comment]
You can use the F5 menu to select factory settings.

**Comment by markusC64** [comment]
Please avoid setting cartridge to "Custom CRT" - that's the configuration that triggers the error.

**Comment by paaco** [comment]
Ah ok, thanks, I was using that precisely to test another FC3 rom.

**Comment by GideonZ** [comment]
1.34 was released, fixing this issue.
