### ISSUE TITLE
Final Cartridge III menu bugged

### ISSUE THREAD

**Issue by Marc91360** [GideonZ/1541ultimate#162]
Hello,

Just updated my U64 Elite to the latest firmware.
When using the "Final Cartridge III", the option menu is bugged. Seems to work, but text is corrupted.

![FCIII](https://user-images.githubusercontent.com/60089223/85728183-f6ae0b00-b6f7-11ea-94ce-5f3b293cedc2.jpg)
![FCIII_b](https://user-images.githubusercontent.com/60089223/85728306-13e2d980-b6f8-11ea-90ab-d101398f741b.jpg)

**Comment by markusC64** [comment]
Confirmed. And observed with **all** FC3 ROMs on my USB Stick.

**Comment by GideonZ** [comment]
This is so so strange.. I can indeed see it now as well, but I have seen it
work before... What happened?!
The good thing is that I made this to run in the simulator, so I can
observe what is going on.

**Comment by GideonZ** [comment]
Fixed in 1.35.
