### ISSUE TITLE
U64 upper/lower case switch

### ISSUE THREAD

**Issue by p2mate** [GideonZ/1541ultimate#168]
using Win + shift on the USB keyboard to switch between upper and lower case doesn't quite work the way using C= + shift works on the C64 keyboard. Just pressing Win + shift does nothing unlike pressing the equivalent keys on the C64 keyboard. However, pressing Win + shift + any non-modifier key results in the case to be switched and the character corresponding to the non-modifier key to be passed to the C64.

**Comment by p2mate** [comment]
The reason for this seems to be that Keyboard_USB :: usb2matrix() only modifies the shift key state in the matrix, if a non-modifier key was pressed.

**Comment by GideonZ** [comment]
Fix was merged, so the issue should be closed.
