### ISSUE TITLE
Error on 1541 emulation devices

### ISSUE THREAD

**Issue by inter981** [GideonZ/1541ultimate#170]
I have a real 1541-II disk drive on #8, an u64 emulation drive (rom 1541-II) on #9 (Enabled), and #10 (Disabled)

When i select a d64 and choose “RUN DISK” option, it allways try to start loading on drive #8, so it doesn’t load: the d64 was mounted on drive #9 (emulated one)

To load, I have to “MOUNT DISK“ and type manually LOAD “*”,9,1 but most of times, starts loading on drive #9 but suddenly changes again to #8, (in the middle of loading process) so it crashes again.

I know I can change drive #8 to #9 on the real drive using back switches (i can because i have a 1541-II version, but it’s not possible in 145I drives)

Can it be fixed to load d64 entirely in the configured virtual drive? (#9, #10 or #11)

Thank you.

**Comment by inter981** [comment]
Any way to backup copy-protected disks using ultimate and a 1541-II?

Thankyou!

Enviado desde mi iPhone

**Comment by GideonZ** [comment]
True! However, some programs use the last used device number, which can be
set in the Ultimate configuration when using DMA. This option is, I think,
in the C64 settings page: "DMA load mimics ID.."

**Comment by Jumpman64** [comment]
Copying protected games never was an easy task. You'll need a real drive with a parallel cable and Burstnibbler. You could try serial nibble copiers too for weaker protections. It's more a question for the facebook group than an issue, it's a wide topic anyway. (I still need to order the U64 Userport Adapter to try by myself how it works out on the U64.)

Here you can get a little overview:
https://c64preservation.com/dp.php?pg=protection
https://c64preservation.com/files/nibtools/readme.txt

and possibly your original is already included as a G64 in e.g. this collection:
https://archive.org/details/C64_Preservation_Project_10th_Anniversary_Collection

even then some tricky protections still won't run in G64 images and emulated environments...
