### ISSUE TITLE
Ultimate64 Regular Hangs / Freezes on Updating Firmware 1.29 to 1.34 

### ISSUE THREAD

**Issue by imstarryeyed** [GideonZ/1541ultimate#183]
Can someone help me understand if I am doing something wrong?

I just got my Ultimate 64 motherboard in yesterday and I successfully installed the .ROM files for the system.

I played a few games and everything worked well.

I installed a brand new ARM2SID chip set into the motherboard and setup the SID chips and it works well.

I then downloaded and tried updating the Firmware on the U64 to the latest one on the website.

update_1.34.u64

When I select the file and choose Run Update the update tool comes up and verifies the checksum of the FPGA image and Application, both say OK

When the box to flash the firmware shows up asking...

About to Flash. Continue
Yes        No

The Yes is highlighted and the system is hung / freezes.

The system freezes before I can hit the Enter key to start the Flashing process so the system does not get flash updated.

I do not yet have my C64 Case and keyboard so I am using a wired USB keyboard.

I have tried : 2 different USB keyboards
2 different USB memory sticks 
Removing the ARM2SID chip set
Setting the system to default

The firmware I am using that shipped with the motherboard is:

   *** Ultimate 64 V1.29 - 3.7 ***

Has anyone experienced this or have a workaround / solution?

The system current is running fine but if I cannot update the Firmware I will not be able to take advantage of the fixes available.

![Firmware129To134Screen](https://user-images.githubusercontent.com/72176407/94758273-57398d80-0362-11eb-8581-0990e1a12c28.jpg)
![SystemHangsAsSoonAsBoxShows](https://user-images.githubusercontent.com/72176407/94758274-57d22400-0362-11eb-8ef5-5d979fd05bac.jpg)

**Comment by GideonZ** [comment]
USB keyboards are not supported in the updater program. You can use a
joystick in port 2 and press fire.

>

**Comment by imstarryeyed** [comment]
Thank you for the info it worked great!
