### ISSUE TITLE
Emulated SID in 1541U2+ does not work in Skyfox

### ISSUE THREAD

**Issue by rittwage** [GideonZ/1541ultimate#185]
When you load the original game, it starts emitting a high pitched sound and never plays the audio during the title screen.

**Comment by markusC64** [comment]
I cannot confirm this. Although audio is quite quiet, it is undoubtedly present on my C128 with 1541 Ultimate II+.

I am testing with the attached image from the original disk.
[skyfox.zip](https://github.com/GideonZ/1541ultimate/files/5397805/skyfox.zip)

**Comment by rittwage** [comment]
I have a second SID in the right channel snooping at $D420. This channel plays such a loud noise you can't even hear the normal Skyfox music in the other channel.  It could be a bug where the game touches the second SID at $D420, but at least with dual regular SIDs or an ARM2SID, it doesn't happen.

**Comment by markusC64** [comment]
Clearly, snooping does not know to differ between I/O access and access to the underlaying ram. Which means that enabling only the channels you currently need is strongly adviced.

There is no known method to differ between I/O access and access to the underlaying ram on the expansion port other then soldering a wire to the PLA output. So Gideon will have no chance to improve that.

**Comment by rittwage** [comment]
Got it, thanks!
