### ISSUE TITLE
Feature suggestion: Add configuration presets for FPGASID

### ISSUE THREAD

**Issue by grue74** [GideonZ/1541ultimate#188]
While FPGASID support is excellent at the moment, I wish there would be possible to have more than an active preset for FPGASID settings, like more pages and active page is saved when exiting the menu.
There are situations where I want 2x6581, 6581+8580, and 2x 8580 too. Then there's also a situation I want my 6581's with different filter curves. 
For example, different filter curves are needed for Rob Hubbard sid tunes and typically more modern ones need different, darker curves.

While these are easily changed already, but it's pain to remember all those good values between listening sessions. No auto-config is needed, but simply the possibility to save more than one set of settings.

**Comment by GideonZ** [comment]
Dear Jarkko,

Your request is fully understood. In fact, you can already do it with the
latest firmwares; I think from 1.26 upward.

> You simply save your configuration to a file and place it somewhere close
to the SID file. Then you can load this configuration any time. You can
name it according to the tune, or to the settings the config file contains,
that's all up to you.
Although this method writes *all* settings, and not just those regarding
the SID, you can edit the config file and remove all the lines with
settings you don't want to change.

Maybe this editing should be possible inside of the "U" as well. I'll
see what I can do to change the built-in file viewer into an editor.

**Comment by grue74** [comment]
Hmm, good idea and it works good enough. I made a few different settings here:
for 8580s, Hubbard, Jeff and Generic.

[fpgasid_configs.zip](https://github.com/GideonZ/1541ultimate/files/5504561/fpgasid_configs.zip)
