### ISSUE TITLE
1541 U II+ ( REU disabled starting .crt images )

### ISSUE THREAD

**Issue by ciccior2003** [GideonZ/1541ultimate#190]
I have tested these:
1) starting ( without flashing ) any type of .crt the REU go off.
To renable the Reu when the .crt image is runing it is possible changing any settings in sub-menu ( C64 AND CARTRIDGE SETTINGS ) for example changing the "cpu adds valid after phi2" ( saving or not new settings ).
It would be perfect if the REU stayed on starting .crt images.

2) flashing as custom CRT the REU go off.
To renable the REU when the crt is running it is possible only choosing Retro replay in sub menu
 ( C64 AND CARTRIDGE SETTINGS ) saving or not changes to Flash 

Thanks

this is my custom .crt  to test if Reu is on https://drive.google.com/file/d/1NApwMOTEx-ruAHbmbR27eyHkZ0OhnZB6/view

**Comment by bvl1999** [comment]
I can confirm this behavior, and the code also shows this is what is happening. 

As a curious detail, UCI remains on (if it was already enabled) when using run cart, but is turned off when flashing the cart and using custom crt rom.

**Comment by GideonZ** [comment]
This is completely rewritten. It does not occur anymore, UNLESS the cartridge in question is incompatible with the REU. Only then, the REU is switched off. Same goes for ACIA, UCI, etc.
