### ISSUE TITLE
3.7: cursor right in menu instable

### ISSUE THREAD

**Issue by Flexmaen** [GideonZ/1541ultimate#191]
I had this problem on my C128 as well as on my C64:

When navigating through the directories on the microSD in my Ultimate-II, using the right cursor can cause the module to get stuck. I figured out when changing the directories with enter+submenu it is reliable.

If you cannot reproduce this you might also try selecting a CRT-file and using the right cursor there.

**Comment by GideonZ** [comment]
Fixed some time ago. Tried to reproduce with 3.10RC and it does not happen.
