### ISSUE TITLE
Feature request: Autoclose option for the User Interface in HDMI overlay mode

### ISSUE THREAD

**Issue by Jumpman64** [GideonZ/1541ultimate#192]
An "exit HDMI overlay user interface after mount/run/etc." option (like it happens in freezer mode) would be very comfortable. Making this optional would be nice if someone still likes to have the overlay interface permanetly open or closing it at will.

> Gideon wrote: "I was getting bothered also by the overlay menu not exiting after mount/run/etc, so yes, I'll have a look at that."

**Comment by Jumpman64** [comment]
@GideonZ Maybe you can have a 2nd look into this issue please. The Ultimate menu isn't closing at all with firmware 3.10, means Interface Type Freezer is now affected too.

**Comment by markusC64** [comment]
Well, I am not sure what behavior is better. Assume you need to insert multiple (i. e. two) disks - in both drives one. Then autoclose is not the best you can think about.

Anyway, having that configurable would solve the different expectations.

**Comment by Jumpman64** [comment]
That's right, that's why i wrote "optional". On the U2(+) the Ultimate application got always closed after mount/run/etc.
My concern was that the HDMI overlay menu does not do the same.
Users now notice that the menu does not close like we are used to. Previously no one complained that the menu closed after a single mount.
Even if you can do crazy stuff on the U64, the C64 is more considered a single drive machine. :)

**Comment by Jumpman64** [comment]
The new option "Leave Menu on Mount" (v1.41-3.10a) solved this issue. Thanks!

**Comment by Jumpman64** [comment]
@GideonZ checked it too quickly. :) if in hdmi overlay, the "Run Disk" command is not closing the menu (there it would be even more logical). Could the autoclose applied to "Run Disk" too like it happens in freeze mode?
