### ISSUE TITLE
Copying GEOS files from d64 to outside an image fails (and other combinations)

### ISSUE THREAD

**Issue by markusC64** [GideonZ/1541ultimate#199]
If I try to copy a geos file from an d64 image to e. g. /temp/ via filebrowser, I just get the error message "Copying error occured. Continue?". It seems that every geos file causes this error.

**Comment by Jumpman64** [comment]
I got this error too today after updating to the latest fw (date 9.2.) 
Can't copy any file from inside a D64 to the Temp RAM DIsk or USB device, After the error message the file gets created with 0 bytes size.
This didn't occur with the other unofficial updates, so i
- flashed the prior unofficial version with resetting the settings, there it works!
- then flashed the latest unofficial verion (9.2.) again with resetting the settings and the error shows up.

Looks like this bug was fixed but sneaked in again?

**Comment by GideonZ** [comment]
Fixed in commit 036c5ff18db5dd01c6db52d672ba0f67e0ac6bea

**Comment by markusC64** [comment]
I have quickly tested this change. Here are my results:

(1) The file I converted to CRT has been converted right. Will have to repeat thatz with more files to be sure.
(2) Copying a CRT from outside an Dxx image to a D64 (I tested with D64) is broken - there is no error message. But Geos does not recognise it as a Geos file.

Given the title of this issue, it has been intended to deal with (2), too.

**Comment by markusC64** [comment]
Ok, have tested other files. There are some geos files which converted to a broken cvt file.

Ultracompare tells me that there are differences in the translated vlir table when comparing to the expected file made with geoconvert64.

**Comment by markusC64** [comment]
And other cvt files are cropped - some bytes are missing at the end.

**Comment by GideonZ** [comment]
>
> (2) Copying a CRT from outside an Dxx image to a D64 (I tested with D64)
> is broken
>

This is not broken; it has never been implemented yet.

**Comment by GideonZ** [comment]
Could you provide example images and tell which file(s) get cropped?

**Comment by markusC64** [comment]
Fur sure

[cvttest2.zip](https://github.com/GideonZ/1541ultimate/files/6074212/cvttest2.zip)

s{65747570}mp64.2.cvt  is cropped.

IIRC geosmp1-1999.pic.cvt gets damaged.


Please use your favourite binary diff tool to compare the CVT files with the espected file that is also contained in the Zip file.

**Comment by markusC64** [comment]
>> (2) Copying a CRT from outside an Dxx image to a D64 (I tested with D64) is broken
> This is not broken; it has never been implemented yet.

I see - in that case the file browser should either provide an error message or copy the file as cvt file to the cbm file system.
Current behevior is that the directory of the disk image is broken after copying.

**Comment by GideonZ** [comment]
First list are contents of the ZIP file:
Second list are the contents of the directory in which all files of
test.d81 are extracted.
I don't see any difference in file size... so how come you say
that s{65747570}mp64.2.cvt is cropped / truncated? In both cases the file
is 3593 bytes.

The files in cvt.d81 are different.  WEll, they have different names.  And
I see that some of those are actually SHORTER than the ones the Ultimate
generates. That is because some of the files have all CVT segments stored
in 'skip' mode. This means that the last segment is actually a skip
section, so the last block of real data is not cropped to the actual size.

The only file differences that I have seen is a difference in SEQ and PRG
in the header.

819200 okt 13 1980 cvt.d81
5842 okt 13 1980 geosmp1-1999.pic.cvt
5842 okt 13 1980 geosmp128+.pic.cvt
2286 okt 13 1980 quickstart-en.cvt
16256 okt 13 1980 readme-en.cvt
99090 okt 13 1980 s{65747570}mp128.1.cvt
3725 okt 13 1980 s{65747570}mp128.2.cvt
94441 okt 13 1980 s{65747570}mp128.3.cvt
13150 okt 13 1980 s{65747570}mp128.4.cvt
5270 okt 13 1980 s{65747570}mp128.5.cvt
16258 okt 13 1980 s{65747570}mp_128.cvt
84417 okt 13 1980 s{65747570}mp64.1.cvt
3593 okt 13 1980 s{65747570}mp64.2.cvt
93831 okt 13 1980 s{65747570}mp64.3.cvt
12487 okt 13 1980 s{65747570}mp64.4.cvt
10212 okt 13 1980 s{65747570}mp64.5.cvt
14332 okt 13 1980 s{65747570}mp_64.cvt
819200 okt 13 1980 test.d81
44450 okt 13 1980 user-manual-en.cvt





5842 mrt 3 09:36 geosmp1-1999.pic.cvt
5842 mrt 3 09:36 geosmp128+.pic.cvt
2286 mrt 3 09:36 quickstart-en.cvt
16256 mrt 3 09:36 readme-en.cvt
99090 mrt 3 09:36 s{65747570}mp128.1.cvt
3725 mrt 3 09:36 s{65747570}mp128.2.cvt
94441 mrt 3 09:36 s{65747570}mp128.3.cvt
13150 mrt 3 09:36 s{65747570}mp128.4.cvt
5270 mrt 3 09:36 s{65747570}mp128.5.cvt
16258 mrt 3 09:36 s{65747570}mp_128.cvt
84417 mrt 3 09:36 s{65747570}mp64.1.cvt
3593 mrt 3 09:36 s{65747570}mp64.2.cvt
93831 mrt 3 09:36 s{65747570}mp64.3.cvt
12487 mrt 3 09:36 s{65747570}mp64.4.cvt
10212 mrt 3 09:36 s{65747570}mp64.5.cvt
14332 mrt 3 09:36 s{65747570}mp_64.cvt
44450 mrt 3 09:36 user-manual-en.cvt

>

**Comment by GideonZ** [comment]
So basically there may be two issues:
- The last segment needs to be detected as such, even if all remaining
segments are in skip mode
- The PRG/SEQ indicator in the header might be wrong.

**Comment by markusC64** [comment]
Let me explain the files that are in the ZIP:

"test.d81" contains the image with the files to be tested.
"cvt.d81" is the same image converted with geoconv64 to cvt as reference. The directory "soll" contains an prg export of that files. Despite the ending, they are cvt files.

The directory "ist" contains what the U64 exported from "test.d81". Note that file names are different from that what geos made. But you can always match files with the cvt header which contains the whole original directory entry.

"prg/seq" on header at the beginning of the header can be chosen on users preferrence in the geos tool, I am ignoring that difference when comparing files. That is a non issue.

**Comment by GideonZ** [comment]
I suggest you to include the 'ist' and 'soll' directories in the zip file.
(At least the 'soll' directory..)
But when I export the files in the cvt.d81 image, I may already have these
files, right?  If my extraction works correctly that is.

When I do that, I get files that are sometimes shorter than the ones that
the U64 generates; for the reason that I mentioned.
I'll have to extend your algorithm to find the last fragment for the cases
when all remaining items are in skip mode.
OK.. having done that, the files get a bit shorter.. See attachment.

**Comment by GideonZ** [comment]
[truncate_fix.zip](https://github.com/GideonZ/1541ultimate/files/6076995/truncate_fix.zip)

Apparently attaching it to the e-mail didn't work. Hereby the zip with the extracted files using the updated algorithm.

**Comment by markusC64** [comment]
Ok, Lesson taken. Never prepare a ZIP file when in hurry before work.

[testcvt2.zip](https://github.com/GideonZ/1541ultimate/files/6077504/testcvt2.zip)

This ZIP is taken from my real working directory - I have one with an older state is well.

**Comment by markusC64** [comment]
Verzeichnis von D:\geos\testcvt2\soll

02.03.2021  19:37    <DIR>          .
02.03.2021  19:37    <DIR>          ..
02.03.2021  19:37             2.099 quicksta.cvt.prg
02.03.2021  19:37             2.099 quicksta.cvt (1).prg
02.03.2021  19:37            16.093 readmeen.cvt.prg
02.03.2021  19:37            44.224 usermanu.cvt.prg
02.03.2021  19:37            14.332 setupmp6.cvt.prg
02.03.2021  19:37            84.417 setupmp6.g98.prg
02.03.2021  19:37             3.593 setupm00.cvt.prg
02.03.2021  19:37            93.831 setupm00.g98.prg
02.03.2021  19:37            12.487 setupm01.cvt.prg
02.03.2021  19:37            10.212 setupm02.cvt.prg
02.03.2021  19:37            16.258 setupmp1.cvt.prg
02.03.2021  19:37            99.090 setupmp1.g98.prg
02.03.2021  19:37             3.725 setupm03.cvt.prg
02.03.2021  19:37            94.441 setupm01.g98.prg
02.03.2021  19:37            13.150 setupm04.cvt.prg
02.03.2021  19:37             5.270 setupm05.cvt.prg
02.03.2021  19:37             5.617 geosmp11.cvt.prg
02.03.2021  19:37             5.617 geosmp12.cvt.prg

vs.

 Verzeichnis von D:\geos\testcvt2\truncate_fix

03.03.2021  17:44    <DIR>          .
03.03.2021  17:44    <DIR>          ..
03.03.2021  15:54               828 s{65747570}mp64.4.cvt
03.03.2021  15:54               828 s{65747570}mp128.5.cvt
03.03.2021  15:54             1.498 s{65747570}mp64.1.cvt
03.03.2021  15:54               828 s{65747570}mp128.4.cvt
03.03.2021  15:54             5.588 geosmp128+.pic.cvt
03.03.2021  15:54             1.050 s{65747570}mp128.3.cvt
03.03.2021  15:54               924 s{65747570}mp64.5.cvt
03.03.2021  15:54            13.416 readme-en.cvt
03.03.2021  15:54            16.258 s{65747570}mp_128.cvt
03.03.2021  15:54               828 s{65747570}mp128.2.cvt
03.03.2021  15:54             1.530 s{65747570}mp128.1.cvt
03.03.2021  15:54             2.286 quickstart-en.cvt
03.03.2021  15:54             5.463 geosmp1-1999.pic.cvt
03.03.2021  15:54            14.332 s{65747570}mp_64.cvt
03.03.2021  15:54            43.988 user-manual-en.cvt
03.03.2021  15:54               828 s{65747570}mp64.2.cvt
03.03.2021  15:54             1.050 s{65747570}mp64.3.cvt

You see, the files MUST be cropped, file sizes do not match at all.

**Comment by GideonZ** [comment]
Ok.. fixed it.. :)  I checked the file sizes, not yet the content. But I am
confident about the content.
Pushed to archive..

**Comment by markusC64** [comment]
Thanks. Currently I am compiling it. And will test it.

Probably with a different disk or different disks so that your test and my test are extending each other.

**Comment by GideonZ** [comment]
Maybe I will look into writing CVT as well. It would be good to have
reading CVT files working perfectly first, so that writing can be tested by
a read-format-write-read-compare operation.

>

**Comment by markusC64** [comment]
Before writing CVT, I should explain (perhaps in a private conversation) you the magic of topdesk folders. You see, having writing support for CVT, you might want to use it to copy whole directory structures.

Anyway, I am verifying my test - I think I have found one file that fails.

**Comment by markusC64** [comment]
Indeed, converting the last file from the d81 fails with an error message for me. The d64 has a copy of that single file and the problem occurs with it, too.
[cvttest3.zip](https://github.com/GideonZ/1541ultimate/files/6078468/cvttest3.zip)

The "ist" directory is empty in this zip on purpose. Created for further tests planed.

**Comment by markusC64** [comment]
Yet another bug:

D:\cvttest5>fc /b is\geosmp1-1999.pic.cvt exp\geosmp11.cvt.seq
Vergleichen der Dateien IS\geosmp1-1999.pic.cvt und EXP\GEOSMP11.CVT.SEQ
000001FC: 00 01
000001FE: 00 01
00000206: 00 01
00000208: 00 01
0000020C: 00 01
0000020E: 00 01
00000210: 00 01
00000214: 00 01
00000216: 00 01

I expect the very same bug happen with the sample disk I have given you - I have tried with the german version, you have got the english version of the very same disk. The image file on it should be the same (unverified).

**Comment by GideonZ** [comment]
> 000001FC: 00 01
> 000001FE: 00 01
> 00000206: 00 01
> 00000208: 00 01
> 0000020C: 00 01
> 0000020E: 00 01
> 00000210: 00 01
> 00000214: 00 01
> 00000216: 00 01
>
Fixed. Changed while(check) { sectors++; } to do { sectors++ }
while(check); // Covers the case of 1 sector correctly.

**Comment by markusC64** [comment]
Great. Will test tommorrow if that fixes the problem found by cvttest3 - unless I am reading the result here at that time.

**Comment by markusC64** [comment]
Next bug - copied from hex editor:

00000000h: 82 0B 10 53 65 74 75 70 4D 50 5F 31 32 38 A0 A0 ; ‚..SetupMP_128  
00000010h: A0 A0 A0 09 00 00 06 15 01 10 0B 00 41 00 00 00 ;    .........A...
00000020h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
00000030h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
00000040h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
00000050h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
00000060h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
00000070h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
00000080h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
00000090h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
000000a0h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
000000b0h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................

Note that Signature  "PRG formatted GEOS file V1.0" resp.  "SEQ formatted GEOS file V1.0" missing - that's interesting.

**Comment by markusC64** [comment]
BTW: You can always use "PRG" or always "SEQ". In the GEOS tool for converting to CRT, the user decides if he want PRG or SEQ files to be created on the conmmodore device. And the type in the HEADER is set in accordance to the cbm file type chosen by the user.

If let's say all HEADERs are expected to be "PRG" ("SEQ" the same) I can make the expected files with that choice, too. Then a simple "sha1sum * | sort" in both directpries "ist" and "soll" allow us to quickly compare the contents. The checksums after sorting should be the same, matching files should be done by sorting.

**Comment by GideonZ** [comment]
Yes.. Interesting. This occurs when the file is not in VLIR format but
sequential. It's a bug that I introduced when supporting the long file
signature (4-block header).   Just fixed it.

**Comment by GideonZ** [comment]
Hi Markus,

I just tried this, and I got a full match on cvttest2 (test.d81), but still
many differences on cvttest3 (gd64en29.d81).

The differences I encounter are:
- There are some SEQ types, while my test program generates PRG only for
now. Generating SEQ only gives some matches, but not all.
- I had to clear out the track/sector numbers in the directory entry.
Something that was not necessary with test.d81.  (Why is this different
between test.d81 and gd64en29.d81?)
- There is a bug in the "expected" files, as I can see that the high byte
of the block count in the directory entry is 0, for a file that is greater
than 64K. So in this case, I am pretty certain that the file in the
expected directory is wrong. File in question: gd_cbm.cvt
- The odd bytes of the extended length block (block #4 of the CVT) was set
to the same value as the odd bytes in the standard length (block #3 of the
CVT); which is the 'last byte in sector' indicator. I don't think it is
wrong, but in the CVTs you provided, these bytes are 0. It was not
specified in the e-mail you sent me, and therefore I assumed these bytes as
don't-care:

Sektor   4 Byte   0/1    Zeiger auf nächsten Sektor = Anfang VLIR-Header.
;                  2-255  VLIR-Datei: Wenn die Datensatzlänger bei
VLIR-Dateien die Anzahl von 255 Sektoren
;                                     überschreibt wird das G98-Format
erstellt.
In diesem Fall wird ein
;                                     zweiter VLIR-Infoblock erstellt.
Parallel zu den max. 127 VLIR-Datensätzen
;                                     erhält jeweils das erste von zwei
Bytes das HIGH-Byte der Sektoranzahl.
;                                     Damit können Dateien mit 127
VLIR-Datensätzen zu je 1-65535 Sektren a 254Bytes
;                                     erstellt werden.

So to my conclusion; you have used two different converter tools, different
versions, or different settings. :-)

Best regards,
Gideon

PS... I think writing is a lot easier than reading, as I can do a fix-up on
file_close( ), after writing all but the first few blocks to the disk
image. Things might get a bit complicated when fseek( ) is called on the
interface, changing parts of the header in a non-linear way.... but maybe I
should just accept that that will probably never happen and accept wrong
results when it does.

**Comment by markusC64** [comment]
> So to my conclusion; you have used two different converter tools, different
versions, or different settings. :-)

Different settings. Changed from "prg" to "seq" settings. Version is AFAIK the same. but I had to reinstall. I have broken my installation in between. That's no problem, I used an older backup and updated to latest version.

Yes, Track and Sector are not relavant for comparing CRT files.

For the other questions, remarks or whatever we may name them I'll ask darkvision, he should know. Since AFAIK he had invented the g98 extension of crt. Therefore I am using his C64 program as a reference.

> - There is a bug in the "expected" files, as I can see that the high byte
> of the block count in the directory entry is 0, for a file that is greater
> than 64K. 

Perhaps. That information is not enough. There is the possibility left in your desciption that every chain is shorter than 256 blocks, but the number of all allocated blocks altogether is greater than 256 (the equal case is clearly not the case).

**Comment by markusC64** [comment]
Ok. In between I build the firmware and installed it.

- The odd bytes of the extended length block (block #4 of the CVT) was set
to the same value as the odd bytes in the standard length (block #3 of the
CVT); which is the 'last byte in sector' indicator. I don't think it is
wrong, but in the CVTs you provided, these bytes are 0. It was not
specified in the e-mail you sent me, and therefore I assumed these bytes as
don't-care:

Not sure. They may be set to the high byte of a value less than 256, so zero. But indeed, I have no info regarding that.

- I had to clear out the track/sector numbers in the directory entry.

I think doing so is a good idea. If we come to that a single geos file has only one CVT representation, that would allow file compare or even checksum of CVT to compare GEOS files. Often one want to know if two GEOS files are the same even when they are stored in different sectors. So yes, filling don't care bytes with a suitable number is a good idea. Zero will do. Doing the same as for cvt vlir record (number of blocks and number of bytes of last block) will also do because they remain the same when relocting to different sectors. But zero is easier to do.

**Comment by GideonZ** [comment]
>
>
>    - There is a bug in the "expected" files, as I can see that the high
>    byte
>    of the block count in the directory entry is 0, for a file that is
>    greater
>    than 64K.
>
> Perhaps. That information is not enough.
>
I think it is enough info... I wrote: in the *directory entry.. *So that is
the last byte of the 30 bytes that the file starts with. It seems that the
last byte is not copied correctly.

**Comment by markusC64** [comment]
Some info from darkvision:

- The odd bytes of the extended length block (block #4 of the CVT) was set
to the same value as the odd bytes in the standard length (block #3 of the
CVT); which is the 'last byte in sector' indicator. I don't think it is
wrong, but in the CVTs you provided, these bytes are 0. It was not
specified in the e-mail you sent me, and therefore I assumed these bytes as
don't-care:

Must be zero.

For writing support: You have to test first if CVT or G98 (is written from byte 30 in a converted file). Afterwards one must act accordingly...


>  think it is enough info... I wrote: in the *directory entry.. *So that is
> the last byte of the 30 bytes that the file starts with. It seems that the
> last byte is not copied correctly.

Ok, perhaps I should recreate that file. Must admit that it has been created about the time I bricked my GEOS installation.

Anyway, we are making big progress - haven't found an obviously wrong file. Consider that directory manipulation has been common, file size information from directory is not trustworthy anyway. So storing it away and restoring it, but not using it anywhere is probably the best way to deal with it.

**Comment by markusC64** [comment]
Only one remark - with lowered priority: The file names from the expected cvt's somehow look nicer in many cases - compare s{65747570}mp_64.cvt with setupmp6.cvt and think it would not be truncated. The original filename within GEOS is "SetupMP_64". So "SetupMP_64.cvt" would habe been the ideal file name. Those filenames are already ASCII, not PETSCII for Geos files - I think the PETSCII conversion is giving those surprising filenames.

**Comment by GideonZ** [comment]
I think this issue is no longer actual. If it is, we can reopen it.

Regarding the last comment from Mar 4 about the PETSCII filename conversion. I understand your request and concern. However, FAT is not case sensitive, so there is no way to store both "SetupMP_64.cvt" and "setupmp_64.cvt" in the same directory, while this MAY be the case inside of a Dxx image.
