### ISSUE TITLE
Problems with the Fast IEC feature

### ISSUE THREAD

**Issue by markusC64** [GideonZ/1541ultimate#200]
Consider the Fast IEC feature. You know, to realize this, the firmware simply writes the device ID of the IEC device into the kernal address $FF80. And unfortunately for every alternative kernal - even if it is not a Fast IEC kernal at all... Honestly, I don't like that. A kernal I load should arrive as it is loaded.

This behavior is bad even for the Fast IEC Kernal. Just think, you would want to try this on a C128, you have your Ultimate II+. I tell you: Will not work. And I really dislike "Will not work".

Because it's like this: Replacing the Kernal with the Ultimate is not possible on the C128. So you do it the classical way, for example with a super kernal. Or by Eprom. It doesn't matter how - that's not the point. What matters is that you replaced the kernal and that the Ultimate can't manipulate $FF80 in ROM. With the consequence that a "does not work" comes out.

Okay - how to fix this?

Consistent reports say that the REU occupies $DF00 to $DF0A. UCI occupies $DF1C to $DF1F.

Thus you could use the address $DF1B to query the set Fast IEC device number, as it is done now unfortunately with the kernal address $FF80. In order to simplify the UCI area (adress decoding), you can even reserve $DF18 to $DF1F for UCI.

UCI must be switched on anyway, so that Fast IEC feature works. So all modules that need the original (unmirrored) REU area $DF00-$DF1F, of which only 11 registers are used, will not work. But this means, if we occupy $DF18 to $DF1B additionally, we don't make anything worse, but we solve the problem with the C128 or the core replacement via eprom / super core / ...

What do you think?

**Comment by bvl1999** [comment]
For using 'fast IEC access' on a C128, you could use https://www.bartsplace.net/content/publications/devicemanager128.shtml
It does not rely on replacing the kernal, and hence does not suffer from the kernal replacement limiations on the 128. It works as a custom 128 external rom.

As to the use of FF80, agree, this is problematic and needs a better solution. DF1B sounds good. Also, reserving upto DF1F does not conflict with the C128 dm rom (it already leaves upto and including DF1F free for this) or the cartridge rom based 'hyperspeed' code I'm currently working on (based on Gideon's modified fc3 code), but did not check that against anything else.

**Comment by markusC64** [comment]
Supporting C128 - very nice idea... But I fear long standing C128 compatibility problems with 2 MHz are to be solved first.

$DF1B writable? Not sure - while your point is valid, there might be accidential changes - I would prefer using a setting where configuration in flash is not updated for temporary changes, so changing iec settings is suitable for a temporary change in my opinion. But YMMV.

**Comment by bvl1999** [comment]
Hmm, 2mhz seems to be no issue for this really, as in.. the code runs totally fine from a custom c128 external rom, and knows itself to switch back to 1mhz for dma (that is needed anyway, you have the same situation when using the REU), and verifies at startup if your 'cpu address ready after phi2' setting is correct (if it isn't, using the function rom at 2mhz will work unreliably). but in and of itself, talking to uci in 2mhz mode seems to work totally fine. 

There are a few hundred downloads now of the latest version of that code (and also of previous versions), of which I know quite a few are in active use. It's certainly not flawless, but none of the issues I'm aware of are related to 2mhz mode.

2mhz is an issue if you want to use the menu, but.. you don't really have to. Solving that would mean solving freezing the machine while in 2mhz. If you happen to use 80 column mode, you really need the 'telnet workaround' anyway, and I'm not sure addressing those things is very realistic, and imo also less important.

At any rate.. agree about accidental changes, hence my suggestion is to very explicitly not write changes to $DF1B back to flash, only update it when the system is started after power-on, and when the user changes it from the menu. So it should behave like 'cartridge ram', not like a writable byte of flash memory.

But being able to temporary change the id used by kernal (and my dm code, and the fc3_wedge) seems quite usefull from my experience, and using some address in system ram for this is bound to conflict with some software (something I'm encountering both with my own 128 dm code, and the fc3_wedge code, both of which can only use either some system ram address, or hardcode it)

**Comment by markusC64** [comment]
> the code runs totally fine from a custom c128 external rom

That is broken... Sometimes (with non neglectable probability, I am observing it with another external function rom) invalid data is read... bit that's yet another bug in another issue.

**Comment by bvl1999** [comment]
I haven't tried that particular rom, but I have totally seen the incorrect reads. 

They can also occur on a C64, but that requires ultimax mode, and vic2 and the cpu accessing the same 256 bytes of rom in their respective phase, so is relatively rare. Some ultimax cartridges suffer from this.

And for pretty much every machine, c64 or c128 I have tried, there is a cpu address ready after phi2 setting with which they do not occur. For that matter, they are reliably reproducable on any machine where this is off, even if it is just one too high or low.

**Comment by bvl1999** [comment]
As to 'run cart', and some carts not working reliably, if that is c128 specific, timing is a safe bet.. but I noticed 'run cart' has a number of bugs, including not disabling UCI when it should, and at least in some cases, leaving the application open while having unfrozen the machine (UII+, or U64 when not using overlay for the menu), both of which may cause issues.

**Comment by bvl1999** [comment]
Ah yes.. there are of course cartridge based games around (like SMB64) which can put a 128 in 2mhz mode, and will crash themselves when run from an image with the UII+, this is generally caused by using a cartridge type which does not have the serve_vic enabled, it would probably be helpfull if that would be enabled for many more cards.

**Comment by GideonZ** [comment]
I think enabling the serve_vic signal should not be enabled by for many
more carts, as it loads the memory significantly, due to the strict timing
constraints. (There is no 'ready' signal on the 1 MHz bus...)

I think it should be enabled if either:
- the user specifies it
- the application detects use on a C128.

**Comment by bvl1999** [comment]
Gideon, that makes perfect sense to me.
It might be useful to also allow the user to change some of the other compatibility settings (such as reu etc).

**Comment by bvl1999** [comment]
@markusC64 yes got it, thank you, I'll take a look at it and see if I either get it to work or get some more clarity on why it fails.

**Comment by bvl1999** [comment]
@markusC64 re: my function rom, yes it should, especially as you explained your phi2 timing settings are already optimal. In fact I am running with VDC output and in 2mhz almost all the time, hence the geos rom thing is quite surprising to me. Anyway, see your mail regarding the geos roms.

**Comment by bvl1999** [comment]
@markusC64 right, I reproduced the issue after a bit of experimenting to get the rom working at all.

As expected, the 1mhz one worked fine, the 2mhz one initially not, through it seemed to get close. After enabling phi2 edge recovery however it works for me, seemingly every attempt of a cold start (tried about a dozen times), but seems dodgy when using the f5, reboot c64 option from the UII+ menu.

Looking at the code I quite suspect the seemingly even stricter timing requirement is due to changing the shared ram size to 8k in the copy code.

**Comment by markusC64** [comment]
Well, C128 differ in hardware timing, on my C128 the 2 MHz version does not work...

BTW: You probably know, the C128 has a warm start vector zjat is used on "reboot v64" because even external cartridges do not disable the warm start vector. Because I have a super kernal 128, I can use it to reset the warm start vector to its successfull started value...

**Comment by bvl1999** [comment]
@markusC64 yes they do somewhat. This does work on both my 128DCRs tho, both PAL machines 9which probably matters a lot here), but only with edge recovery enabled, it seems to really push the limits on this.

Wondering, do you happen to have a 256k ram expansion by any chance?

**Comment by bvl1999** [comment]
As to warm start, curiously it works fine on a regular reset, only seems dodgy after using reboot 64 from the f5 menu.

**Comment by markusC64** [comment]
Well, I'm pretty sure GeoROM changes Warmstart. And it might do so also when crashing.

Regarding RAM expansion, I do have a real GeoRAM (very rarely used) and all that the Ultimate can emulate. Nothing more.
If I need a RAM Expansion, I'd probably integrate it in the U2 - like I already have done a few years ago with GeoRAM.

**Comment by bvl1999** [comment]
@markusC64 clear. My question was because the 256k ram expansions mess with the MMU (to make bit 7 of the cr register functional) and likely also affect timing as a result.

**Comment by GideonZ** [comment]
UCI was extended from 4 to 8 bytes. One additional byte is used for the SoftwareIEC drive number ($DF1B).
UCI kernal has been adapted to reflect this change, and seems to be working alright.
