### ISSUE TITLE
48MHz vs dot clock 

### ISSUE THREAD

**Issue by p-a** [GideonZ/1541ultimate#203]
I would like to think that setting the turbo register to 48MHz and having a small loop like
```
LDA #$00
STA $d020
LDA #$01
STA $d020
```
would produce a screen with alternating black and white "pixels", but at every 48:th or so there is a glitch in the pattern, making me think that it isn't in sync with the dot clock:

![image](https://user-images.githubusercontent.com/1712378/104136303-87e38700-5395-11eb-941d-3fa780537fd3.png)
(Sorry for half-baked screenshot, but you should get the gist)

Ultimate 64 V1.37 - 3.9. PAL. HDMI.

**Comment by GideonZ** [comment]
The system is in sync with the DOT clock. However, you should not forget
that the VIC also steals cycles from the bus.
So basically, when the screen is off, you will get 47 cycles for the CPU /
MHz. You could argue that this wouldn't be necessary, but that's the way it
is right now. The original half cycle where PHI2 = 0 is always a VIC cycle,
also at 48 MHz, also when the screen is off.

**Comment by p-a** [comment]
Okay! Makes sense I guess. Thanks!
