### ISSUE TITLE
HOME function in user interface no longer works 3.9 U2Plus

### ISSUE THREAD

**Issue by russelkent** [GideonZ/1541ultimate#208]
If you press middle bottom fast direct (cold start) when it works
![IMG_20210211_060436](https://user-images.githubusercontent.com/78894700/107604668-19624500-6c31-11eb-99b6-b6fd5e1d1619.jpg)
![IMG_20210211_060555](https://user-images.githubusercontent.com/78894700/107604670-1a937200-6c31-11eb-8499-ff0814e2b1e6.jpg)

**Comment by GideonZ** [comment]
Reproduced and fixed. 
Should work again in 3.10.
