### ISSUE TITLE
commit ab86b15a22fcbe6be797bb55d5f23dc4dfa88397 breaks build

### ISSUE THREAD

**Issue by p2mate** [GideonZ/1541ultimate#211]
commit ab86b15a22fcbe6be797bb55d5f23dc4dfa88397
Author: GideonZ <gideon.zweijtzer@gmail.com>
Date:   Tue Feb 9 16:51:03 2021 +0100

    Updates to tester software.

Adds

```
#if U64
#include "u64_machine.h"
#endif
```

to software/io/c64/c64.cc and 
```
#include "u64_machine.h"
```
to software/u64/u64_machine.cc

However, u64_machine.h is not part of the repo. I guess it was not added to the repo by mistake?

**Comment by markusC64** [comment]
Confirmed. Cannot build.

**Comment by GideonZ** [comment]
The file u64_machine.h has been added.

**Comment by p2mate** [comment]
perfect! thank you. 
closing.
