### ISSUE TITLE
Long file name, can name be scrolled?

### ISSUE THREAD

**Issue by Mclaneinc** [GideonZ/1541ultimate#212]
I love my 1541 Ult++ but with long file names I can't always tell if I have the right disk.

I've search the docs but can't find a way to do it..Would it be something for the future?

Thanks

Paul...

**Comment by Jumpman64** [comment]
...or maybe just a simple "Show filename" menu option would be sufficient, like viewing textfiles. 

You could use "Rename" as half working work-around if the name isn't longer that 38 chars but an option to display the whole name would be great indeed.

**Comment by Mclaneinc** [comment]
Yup, a simple show name would be great, on my AVG cart (atari 8 bit) the author just added a key press to show the other half of the name. Scrolling looks more professional but a key press would more than enough..

Thanks for the work around..

**Comment by GideonZ** [comment]
The associated pull request was merged into the development branch. Feature should appear in 3.10.

**Comment by Mclaneinc** [comment]
Thanks to all involved..
