### ISSUE TITLE
SoftIEC setting STatus different to other Kernals

### ISSUE THREAD

**Issue by cbmbas** [GideonZ/1541ultimate#220]
It seems we found a Bug in SoftIEC Kernal. Maybe you can have a look at it. When copying Data from 1 SEQ File to 2nd SEQ File, the ST Variable seems to be set different than usual, maybe earlier ?!. This results in broken copies (last record missing, previous record double). I wrote a short BASIC Prg to demonstrate that. It fails in SoftIEC and in SoftIEC within a D64. Works with JiffyDOS f.e. on U64 100%. Bug also happens with REL Files f.e. when building a new REL File from a SEQ File (C*BASE Userlog).
[seqtest.zip](https://github.com/GideonZ/1541ultimate/files/6274023/seqtest.zip)

**Comment by GideonZ** [comment]
This was not a status (ST) problem, but a problem with the assumption that all data was read by the computer when an 'abort' occurs, when it was the last data block of the complete file.  Fixed.
