### ISSUE TITLE
Creating G64 images in a row crashes the Ultimate application

### ISSUE THREAD

**Issue by Jumpman64** [GideonZ/1541ultimate#226]
latest_unofficial_u64.zip 07.03.21

steps to reproduce:
- turn on your U64, go to a directory
- create a G64 named e.g. 01.g64
- don't move and create another G64 named 02.g64
then the Ultimate application freezes or/and crashes to black screen and you need to turn off the U64. 
After restart you'll see the 02.g64 with 0 bytes.
Moving the marker between creating G64 images seems to prevent this temporarily. 
Seems it doesn't happen when creating other image types.
While creating a G64 there is a double progression bar, is that for a reason?

**Comment by GideonZ** [comment]
The double progress bar was not the reason. What the reason was exactly remains unknown, but after rewriting much of the disk image code, this does not seem to happen anymore. This issue can be reopened when necesasry. Double progress bar has been fixed.

Should work in 3.10.
