### ISSUE TITLE
Ulticopy - Suggested Name fails to update

### ISSUE THREAD

**Issue by QuillOmega0** [GideonZ/1541ultimate#227]
On latest release of U64 firmware (3.9 / 1.37) the suggested name from the disk directory title, fails to update after the copy of the first floppy. This is the case whether doing batch copying, or starting a new copy process entirely.

Name suggestion works on the first disk after a fresh boot but fails to update after the first disk and will always suggest the same file name as was suggested before.

**Comment by Grrrolf** [comment]
I confirm the issue as described above. The disks I copied have different disk labels/names. 
This happens when "Ulticopy Uses disk name" is enabled.

**Comment by GideonZ** [comment]
Fixed in commit ad3ee0a.
