### ISSUE TITLE
1541 Ultimate ii 3.10 update drive sounds problem

### ISSUE THREAD

**Issue by psy6** [GideonZ/1541ultimate#232]
Hello , I got distorted drive sounds after updating my old ultimate ii with 3.10 firmware and after i trigger the settings (audio left right sound etc menu) most of the time i get no drive sound at all.
Another issue is that you can not downgrade the firmware cause the 1541u2 freezes after update loading.
thank you .

**Comment by GideonZ** [comment]
Not even by placing the older updater on the SD card, naming it
"recover.bin"?

**Comment by psy6** [comment]
With the 3.7 update renamed recover.u2u and copied on root of sd card it freezes upon boot on basic screen.

**Comment by markusC64** [comment]
Regarding downgrade impossible: I can reproduce it here. Downgrade to 3.7 and older is impossible.

But interestingly, a downgrade to the on the u2 never released version 3.8 (build from sources when it was up2date) works. And from that build, I can downgrade further.

I remember between 3.7 and 3.8(? unsure about exact version) there was an issue on the U2+ making some installers freeze... and older installers naturally do not contain the fixes made at that time.

**Comment by psy6** [comment]
(Note that i have an old ultimate ii not the plus) Managed to downgrade with an old firmware i had version 3.0b7 and then updated to 3.7.

**Comment by markusC64** [comment]
Doubltless we speek about the U2 without Plus. The Reference to the U2+ was only for Problems with interim alpha versions where U2 was not tested.

**Comment by markusC64** [comment]
I think I have remembered what was the problem with the U2+ - quite likely now we have the same problem with the U2:

The older installers (3.7 and older) read out the configuration area of the flash to extract border-, background- and foreground color. If they do not understand the config, they crash.

Starting with installer 3.8, we had changed that not to access the configuation area.

Quite likely the old installers do not understand the current configuration...


This also explains why downgrade to 3.8 and then to 3.7 helps - installer of 3.8 ignores the configuration areas content. And the firmware writes a configuraion which is similar enough to be understood by 3.7 and probably older installers.

**Comment by GideonZ** [comment]
That would be a possible explanation. However, it is more likely that there
is an interrupt that triggers, which is not handled by the older firmware.
Everything needs to be properly disabled. It is possible that this has
landed in the "filetype_u2p", but not in the "filetype_u2u" handler. I
noticed that they are different; because one has a progress bar while
loading, while the other doesn't.

**Comment by markusC64** [comment]
Well, U2+ Installer 3.7 also crashes... So I would not think difference in filetype_:u2p and filetype_u2u is the reason.

**Comment by psy6** [comment]
You can downgrade from latest 3.10 to 3.0b7 and then to 3.7 i’ve done it and it works for me , now i’m on 3.7

**Comment by CRP** [comment]
I also experience distorted drive sounds since upgrading to 3.10 on my ultimate II.

**Comment by yucelbilik** [comment]
There is a note on the cartridge update."There is one special version of the 1541U2 that supports GMod2, at the cost of other features." what does it mean?

**Comment by Pontiac76** [comment]
I'm not seeing a 3.0b7 under GideonZ or marcusc64.  Not in the tags, and not in the release history.  I've gone back to the original release by Gideon as posted here in Gideons repo, and I'm still hitting a brick wall with the system doing the reboot and hard-locking at the 64 screen when trying to go back to previous versions.

I did find on Gideons Github a 3.0beta7, looking at the contents of the zip file it LOOKS to be for the Ultimate2, not the Ultimate2+, which as I understand it, should NOT be used on a U2+.

**Comment by markusC64** [comment]
Here you are: https://github.com/GideonZ/ultimate_releases/blob/master/1541u2_3.0beta7.zip

**Comment by psy6** [comment]
Bump just to bring the thread back to topic about the distorted drive sounds :)

**Comment by michas0602** [comment]
Same here, they sounded louder directly after the update, now they sound normal after some days of use...not sure whats causing the difference in volume or what I did exactly to get them back to normal - but there are definately differences with 3.10.

**Comment by psy6** [comment]
Fixed with 3.10a update , thank you.
