### ISSUE TITLE
Confirmation modal asking a question only gives 'OK' instead of 'Yes/No'.

### ISSUE THREAD

**Issue by Grrrolf** [GideonZ/1541ultimate#236]
**_This applies to firmware 3.10; I did not test on previous firmware versions_**

Using the remote menu via telnet I accidentally pressed ctrl+t. This is a short cut to set the current dir as home dir and is new to me. 

![image](https://user-images.githubusercontent.com/10052794/126915283-9a826013-1d49-4786-b598-ea10f49829bb.png)

This also applies to the Ultimate menu itself when pressing cbm+t:
![image](https://user-images.githubusercontent.com/10052794/126915326-cad90c2b-e90e-4f83-98f5-c8ff9383b9b8.png)

The expected behaviour would be that it would give me a choice between [ yes ] and [ no].
I don't use the 'home directory' option and would like to be able to answer no. There is no way to 'escape' this modal.

When checking whether the home dir has actually been set, it turns out it has:
![image](https://user-images.githubusercontent.com/10052794/126915483-add1b810-3c48-4521-a6cd-a17fe9ed0f12.png)

I have two suggestions (without having any knowledge of what is possible):
1. make it a confirmation modal which tells that the current dir is set as home dir. Not asking a quesion makes using only [ OK ] as expected.
2. allow for a yes/no answer in the confirmation modal where the question 'set current dir as home dir?' stays. This allows one to decline setting the current dir as the home dir directory.

So long as the end user does not have the 'Enter Home on Startup' enabled, it doesn't break anything when choosing suggestion one.

**Comment by GideonZ** [comment]
Fixed in commit dac8b5eb. Version 3.10a
