### ISSUE TITLE
System freezes when entering u2+ menu when enter home at start up is enabled

### ISSUE THREAD

**Issue by thomasf** [GideonZ/1541ultimate#24]
The ultimate menu screen is shown when pressing the middle button and the Usb0 or 1 device is listed but the UI and the cartridge buttons stops not react on input so the computer has to be rebooted to work again.

It happens often but not all the time. Pressing the "home" button on the keyboard works. My home is simply the root of either usb0 or usb1.

I have not been able to reproduce the problem if I disable the "enter home directory at startup" option. I've tested with the default u2+ usb stick and the kingston stick I bought with the U2+ in both usb0 and usb1.

So I'm guessing it's some kind of race condition, maybe the device is trying to enter the directory before the files ystem access is properly initialized or something...

**Comment by thomasf** [comment]
I think it's the latest release firmware, at least 3.2 (from a few weeks ago). I'll verify that later today.. Is there anything I can do to debug the situation?

I think the problem has been showing up more often the more files I have on the usb stick but I can't say for sure.

**Comment by thomasf** [comment]
The firware is 3.2a.. 

How do you know that 25 is the correct value?

I can try to increase it to see what happens.. I haven't really set up my build environment correctly yet, I will try to do it this weekend so that I can try to modify the delay value..

**Comment by GideonZ** [comment]
Possibly this is caused by concurrent file access from multiple threads?
This has not been fully validated yet...

**Comment by Grrrolf** [comment]
Use the released firmware instead of trying to compile it from sources yourself. It will safe you a lot of time. The firmware was released on the 1541ultimate facebook page. Have a look here if you don't have facebook:  https://ammo.home.xs4all.nl/Ultimate_Carts/firmware_ultimate_carts.html#toc_1

**Comment by markusC64** [comment]
Anyway, firmware release 3.3 corresponds to commit ccf93a4cbac8118afe1351ba4b3bbf53461be525. You can compare to my repository, it has tagged that release: https://github.com/markusC64/1541ultimate2

**Comment by thomasf** [comment]
Well, I can't seem to reproduce it on 3.2a right now.. Don't want to power cycle the computer a bunch of time just to test it so I'm closing this issue.. Will reopen if the problem recurs again with the new firmware.
