### ISSUE TITLE
Maverick/1581 toolkit: emulated 1581 write troubles. 

### ISSUE THREAD

**Issue by Flaviowebit** [GideonZ/1541ultimate#240]
If, using Maverick 5.04 or 1581 toolkit, we try to make a copy of a disk from a real drive or an emulated drive to an emulated drive, we will get a destination disk that will contain an alternation of data and sequences of $00 every $1400 bytes.

Instead copying from fpga to real drive will only work with 1581 toolkit while it will break after a few tracks with Maverick (so I guess Maverick bugs are also involved).

**Comment by Flaviowebit** [comment]
Update:
Maverick is developed on NTSC machines... so maybe main problem is this and not a bug in Ultimate 1581 emu.
I'm not 100% sure but i've tested using Vice and, in Pal, copy didn't work at all. On NTSC (Vice) copy disks generating same wrong data as Ultimate 1581 does.

**Comment by Flaviowebit** [comment]
Update2:
Maverick or 1581 toolkit can copy disks from FPGA to real 1581 even on PAL and NTSC machines.
Backwards, from 1581 to FPGA generate wrong images contain an alternation of data and sequences of $00 every $1400 bytes.

**Comment by GideonZ** [comment]
Maverick is faulty. It formats side 1 with sector headers that say that it is side 0. The destination disk is therefore actually wrong.

However, turning off the check for the side when looking for a sector solves the disk copy problem. 

Fixed in 3.10a.
