### ISSUE TITLE
10 years HVSC 1581 disk image does not work

### ISSUE THREAD

**Issue by p2mate** [GideonZ/1541ultimate#244]
https://csdb.dk/release/download.php?id=53327 starts, but when pressing space at the intro screen, the screen eventually changes to cycling colours.
The 1571 and 1541 images work correctly.

**Comment by GideonZ** [comment]
The same happens in VICE.

**Comment by p2mate** [comment]
hmm, maybe the image is broken then. I don't have a real 1581 to test :)

**Comment by jaluth** [comment]
@p2mate Try skipping the intro and load the "10 YEARS MAIN" file directly. That worked for me (although I had to test it in VICE 3.6-GTK as there's no D81 support on the 1541 Ultimate II firmware.)

**Comment by Grrrolf** [comment]
Now it has been determined that the release on the 1851 medium is actually broken and a workaround has been provided, it would be a good idea to close this ticket.

**Comment by p2mate** [comment]
Loading "10 YEARS MAIN"  directly indeed works. The ultimate 64 has a reset option under F5 -> drive A but it doesn't help.
Closing.
