### ISSUE TITLE
1541U II, 3.10 JiffyDOS problem

### ISSUE THREAD

**Issue by jackszew** [GideonZ/1541ultimate#245]
1541U II, 3.10. (without a plus).
JiffyDOS, JaffyDOS ROM as alternate kernal hangs when trying to read from disk, no communication. Only tested on an emulated drive with a normal ROM and JiffyDOS1541.rom.
In 3.7 everything works fine.
Please confirm if anyone has a similar problem. Thank you.

**Comment by Grrrolf** [comment]
Have you fixed the problem? If so, are you willing to share what the issue was and how you solved it?

**Comment by jackszew** [comment]
There is a problem with the computer, I tested it on C64.  Everything works fine when connected to the C64C.  I still do not know what the problem is, the C64 computer without the 1541U or with a different cartridge works fine.
