### ISSUE TITLE
Alternate Kernal crashes on U2 3.10a

### ISSUE THREAD

**Issue by jpcompton** [GideonZ/1541ultimate#251]
I just updated both my U2 and U2+ to 3.10a. (Gmod variant selected for U2.) On two different NTSC C64s (classic 64 and 64C), the Alternate Kernal feature no longer works on the U2. (C64 crash/lockup when any kernal selected, Ultimate menu continues to work fine.)

On the same two host machines, Alternate Kernal (with the same Jiffy kernal image) *does* still work on the U2+. Apart from the host machine, the configurations are identical: they are being tested on the same PSU, with no other peripherals attached other than the relevant Ultimate cart.

Tweaking PHI2 enable/disable and timing does not appear to make any difference. 

Update: It was recommended elsewhere that I try re-flashing the 3.10a firmware. This did not improve the situation.
I took the opportunity to try all three flavors of 3.10a U2 firmware.
This, also, made no difference.

**Comment by jpcompton** [comment]
Works in 3.10i.

**Comment by marty41** [comment]
Then please close you issue. ;)
