### ISSUE TITLE
Feature Request: View contents of an diskimage directly in the filebrowser of U2+

### ISSUE THREAD

**Issue by tenuke** [GideonZ/1541ultimate#256]
I have now archived some 2000 floppies and would love to be able to see the contents
of .d64 image straight in the filebrowsing menus of the Ultimate-II+ preferably with some quick key.

What I now have to do is quite a lot of steps to get to just see what is inside some image..
1. mount the random image
2. menu button on u2 to exit the menus
3. reset button on u2 to get to virtual retro replay cartridge,
4. f7 to install fastload
5. f3 to load&view the contents of the image..
.. and then back to menus to rinse & repeat to check another image

Thank you a million if you are able to add this some day!

**Comment by GideonZ** [comment]
How about crsr-right? You can just enter the image as if it was a directory.

**Comment by xlar54** [comment]
This ticket can be closed.  As Gideon says, you just need to csr-right on a disk image to see the contents
