### ISSUE TITLE
Data stream feature gone?

### ISSUE THREAD

**Issue by marcopiraccini** [GideonZ/1541ultimate#258]
I have read the doc, and apparently I should be able do do data streaming (I would like to open a stream directed to my linux laptop).  
However, when I click F5 the VIC options are not in the action menu. What I am doing wrong?

Maybe this feature has been removed?
I am using the 3.10a firmware on a Ultimate II+

**Comment by GideonZ** [comment]
There is no VIC stream on the Ultimate-II+.

**Comment by marcopiraccini** [comment]
Ah OK, sorry, I didn't catch this from the doc. 
Closing this.
