### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#26]
Im interested in working on the code for the apps (not FPGA).  But Ive never done FPGA development before.  Will this build a standard U2+ update file, or more lower level than I currently understand?

**Comment by markusC64** [comment]
Yes, from the source code, you can build usual update files for U2 and U2+.
In development, you can use an USB BLASTER  to start an application on the U2+ with the make target "u2plus_swapply" - which is much faster than compling everything, copy it to the U2+, run the updater. This way, the application IS NOT flashed to the U2+, so it's only good for testing while developing.

Note that you cannot build an updater for the Ultimate 64 from the sources - you need an additional FPGA image for the Ultimate 64, too.

**Comment by xlar54** [comment]
Understood and closed.  Thanks MarkusC64
