### ISSUE TITLE
Freeze button non working when running a game [UII+, 3.10a]

### ISSUE THREAD

**Issue by marcopiraccini** [GideonZ/1541ultimate#264]
To reproduce: 
- Start the C64 with UII+ with Cartrdige set to "final cartdrige" or "action replay" (same behaviour with both) 
- If I click the "freeze' button, I see the cartdrige menu in both cases
- Then I run a disk from Ultimate II+
- The game starts correctly
- I click on "freeze" and nothing happens
I this supposed to happen? Or I am doing something wrong?

**Comment by marcopiraccini** [comment]
Tnx, closing.

**Comment by Gun-neR** [comment]
And after a lot of searching ("freeze" is a multi-meaning word here) I also thank you for this answer, some 3+ years later... It was driving me buggy.
