### ISSUE TITLE
Ultimate 64 Elite - issue with SuperSnapshot 5 NTSC Black Screen not booting

### ISSUE THREAD

**Issue by uttini** [GideonZ/1541ultimate#273]
Ultimate 64 Elite V1.41 - 3.10c
2 real SIDS (6581 in socket 1 and 8580 in socket 2)

When SuperSnapshot 5 is selected as a booting cartridge in the Ultimate Menu, the C64 boots to a black screen. 

I have the motherboard speaker installed and I can hear the drive active sounds, and a video signal is sent to the monitor but its just black and no C64 boot screen. I can still get access to the Ultimate menu by pressing the power button. Once in the menu I can reset or reboot the C64, and it works normally. But as long as I have Supersnapshot set as the booting cartridge, I can not start the Ultimate 64 from the power button on a cold start without first getting a black screen, and then having to launch the Ultimate menu, and then going from there.

I did a bit of troubleshooting as I suspected that the dual SIDS were causing this as I was aware of a similar issue reported with the EPYX cart. And sure enough, that seems to be the issue here. 

First I disabled both Socket 1 (6581) and Socket 2 (8580) and that fixed the issue - and the computer booted normally with SuperSnapShot running normally and a normal C64 blue boot screen. 

Next I activated only Socket 1 (6591) and kept Socket 2 (8580) disabled, the computer booted normally with SuperSnapShot running normally and a normal C64 blue boot screen. 

Next I disabled Socket 1 (6591) and enabled Socket 2 (8580) and that made the problem reappear. So it seems that the issue isn't dual sids but rather an issue that the ultimate 64 has that is particular to the 8580 sid chip - while cold booting with an attached cartridge image.

**Comment by marty41** [comment]
Sounds to me like you are using an address range for SID2 that also is used by your activated cartridge. 
You did not provide any information about the address ranges the two SIDs are configured.

**Comment by uttini** [comment]
Good suggestion - which led me to more troubleshooting. Unfortunately, I was using the same address for each SID Socket. SID socket Number one was mapped to $D400 and SID socket two was also mapped to $D400.  Also UtiliSID 1 & 2 are also mapped to $SD400. I never had more than one SID active at one time. The 6581 works fine, and the UtiliSID works fine using $SD400 - however the C64 will not boot when 8580 is enabled with $SD400 - I get the black screen at boot up. So I went in and remapped Socket #2 the 8580 to $DFE0 and lo and behold the C64 boots normally without the black screen. Not sure why $D400 works with the 6591 and not the 8580 - I would assume that SS5 cart would use the same address regardless - so it doesnt make sense why the same address will sometimes conflict and sometimes not depending on what SID is active.  Not sure why or how SS5 would know or care what version of SID was active since its the same functionally. 

In any event I am going to leave it this way now with Socket #2 (8580) mapped to $DFE0 as its now working. Just wish I knew what the true nature of the issue is that's causing it. 

Thanks again for the suggestion marty41 - definitely helped me and it wasn't something that I thought of.

**Comment by Grrrolf** [comment]
> Thanks again for the suggestion marty41 - definitely helped me and it wasn't something that I thought of.

If your issue has been solved, then please close the ticket.
