### ISSUE TITLE
U64: Comaland disk 3 'screen wobble' part VIC bugs on the right side

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/1541ultimate#281]
The Comaland demo has a VIC bug on the right side of the screen in the 'screen wobble' part.

![image](https://user-images.githubusercontent.com/7808413/189062871-e812e4df-eac8-4a2a-ab69-8f18cc5bc1c9.png)

Latest 3.10c firmware on newest U64 Elite 1.41

**Comment by GideonZ** [comment]
Fixed in V1.42.
