### ISSUE TITLE
FR: Keyboard shortcut to mount next floppy image on U64

### ISSUE THREAD

**Issue by gobalius** [GideonZ/1541ultimate#282]
On 1541ultimate it's possible to mount the next floppy by pressing the middle button for 2 seconds. This enables viewing of demos without freezing the emulation. Some demos are sensitive to freezes and a lot have a nice music playing during the "turn disk" phase. So, no interruptions is very nice to have.
Could we get for Utimate 64 implementation of frezeeless next floppy mount as a keyboard shortcut. For example "Ultimate 64 multi-button (power button, haha) and D"?

**Comment by GideonZ** [comment]
Ctrl-D already works (on a USB keyboard)

On U64 you can use the overlay menu to avoid freezing.

**Comment by gobalius** [comment]
@GideonZ thank you for replying. I was hoping for a solution that doesn't require a USB keyboard and/or HDMI output. I like to use my U64 with a CRT display, RGB analogue output, etc. To not really notice that it's not a real C64. ;)

**Comment by GideonZ** [comment]
The keyboard scanning is done by the C64, so this cannot be intervened
while the demo is running.

**Comment by gobalius** [comment]
I see, I'm wondering now though... how does "POWER + RESTORE" then work for freezing? Is RESTORE key special in some way?

**Comment by GideonZ** [comment]
Yes. the restore key is a separate line that - on a real C64 - is connected
to the NMI signal.

**Comment by gobalius** [comment]
Many thanks for your time @GideonZ 
Closing the issue.

**Comment by p-a** [comment]
@gobalius 
Perhaps something like this could fit your use-case?

https://www.amazon.com/Ecarke-Mechanical-Keyboard-Programming-Software/dp/B09TMVXNGG/
