### ISSUE TITLE
U64: Booze - 30 Years Bob Display VIC problem

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/1541ultimate#284]
In the Booze Design - 30 Years demo there is a problem with the Bob part - there are big horizontal glitches.

Demo: https://csdb.dk/release/?id=219292

![image](https://user-images.githubusercontent.com/7808413/189062695-de1f8e08-5638-4d75-ac38-07d10138f6fe.png)

U64Elite v1.41 - 3.10c

**Comment by GideonZ** [comment]
This is the same in VICE when you select the old CIA (6526). The U64 implements this type of CIA.
There is a bug-fixed version of this demo, which runs fine.
