### ISSUE TITLE
U64: XXX demo by Lethargy twister part very Jumpy VIC problem

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/1541ultimate#286]
In XXX demo by Lethargy the last effect on disk 1 (4x4 twister) is VERY jumpy, should be stable, but the screen is jumping up and down all the time.

Demo: https://csdb.dk/release/?id=207188

Picture: 
![image](https://user-images.githubusercontent.com/7808413/189062007-4435fea2-c1fe-49ff-9d75-af39a9b10f56.png)

U64Elite 1.41 - 3.10c

**Comment by slc79** [comment]
Can confirm this happening also on a real C64 with the older CIAs.

**Comment by GideonZ** [comment]
Since this behavior is observed on a real C64, it is not an U64 issue.
