### ISSUE TITLE
U64: Custom palette does not effect Video Stream

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/1541ultimate#291]
When having a custom palette selected (for example pepto.vpl) this is not being used on the video stream, the default palette is used always.

U64 1.41 - 3.10c

**Comment by GideonZ** [comment]
... as stated in the documentation, yes.
The color palette information is not part of the stream data; only nibble
color pixel values are, so the colors are converted by the viewer.

**Comment by TomCat666** [comment]
Of course, not reading the documentation :) Somehow I thought the stream was normal video stream. Closing the issue.

Definetly need to read through the WHOLE documentation. RTFM as they say. :)
