### ISSUE TITLE
U64: Wildbunch demo twister problem

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/1541ultimate#292]
Wildbunch demo by Focus,... : https://csdb.dk/release/?id=41462

In the twister part right on the edge where border starts there is a corruption:

![image](https://user-images.githubusercontent.com/7808413/190970614-40160818-127a-46a6-8b1c-5aa9b8c8ca43.png)

It seems this might be a similar problem to Comaland, one byte problem right before the border starts...

U64 1.41 - 3.10c

**Comment by GideonZ** [comment]
Fixed in V1.42
