### ISSUE TITLE
View menu option doesnt appear to do anything

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#30]
Locate a D64 image, hit enter, menu pops up (Mount Disk, Run Disk, etc).  Select View.  The logical assumption is that this will let you see the disk directory, but its empty.  V3.3 (112)

**Comment by GideonZ** [comment]
The "View" option opens the file in the text editor. It may show whatever junk is in the first sectors of the file. The editor ends at the first encountered 0x00 byte, so if the first sector is empty, you will see an empty screen. So this is not an issue, but expected behavior.

**Comment by xlar54** [comment]
I see, thank you.
