### ISSUE TITLE
Edge of Disgrace fails (U64 + virtual 1541)

### ISSUE THREAD

**Issue by Jusalak** [GideonZ/1541ultimate#303]
Hello,

Edge of Disgrace fails on U64. After disk swapping to 1A and soon, after the stars part, the screen remains blank red. Music may continue playing, but nothing more is displayed.

[EdgeOfDisgrace.zip](https://github.com/GideonZ/1541ultimate/files/10262269/EdgeOfDisgrace.zip)

I intend to test real HW but I have trouble copying those .D64 images back to real floppies. But I suspect that a real C64C + 1541II should run it.

Jussi Ala-Könni

**Comment by Grrrolf** [comment]
Which firmware are you using and did you switch off all other devices on the IEC bus? If you have an external drive connected, disconnect it. Do you use by any chance a custom kernel? Try using a vanilla kernel instead.

**Comment by Jusalak** [comment]
Latest 1.41 - 3.10c, with stock Commodore Kernal.
IEC is disabled, external drive turned off, but serial cable physically connected.
I tried it again, it ran correctly.
Then I powered U64 off and on, tried again, and it failed.
So one time it runs, other time it fails.

**Comment by Jusalak** [comment]
With the serial cable unplugged, the problem has so far not appeared again. Even when the drive is turned off, the presence of the serial cable makes some tiny bit of difference.

**Comment by markusC64** [comment]
I think it's not the presence of the iec cable, but the presence of the turned off floppy. You see, it pulls signals to zero. Depending on the device, not completely, but it does. This is frequently breaking things even on a real C64 / C128.
