### ISSUE TITLE
new feature: play/run TAP files via network (socket_cmd)

### ISSUE THREAD

**Issue by 4ch1m** [GideonZ/1541ultimate#311]
Hey there,

the 1541ultimate/Ultimate64 already has a few awesome network features; like sending and running PRG and D64 files (via `SOCKET_CMD_DMARUN` and `SOCKET_CMD_RUN_IMG`):

   https://github.com/GideonZ/1541ultimate/blob/27951e6bf9babc4982a7c5197ebcf461efdd13eb/software/network/socket_dma.cc#L22-L35

Would it be possible to also add support for TAP files as well?

Tape support is already present and working fine in the user interface; where it's already possible to select a TAP file and run it.

Making this available via socket command would be great.

(Note: This may also mean to loosen the 200 kilobyte limitation for the payload; since some TAP files can reach up to 1 megabyte.)

Thanks!

**Comment by 4ch1m** [comment]
Oh, I just read issue #285 and realized that the `socket_cmd` feature might be removed/replaced at some point.

So... it would be cool if a "run tape" endpoint would be considered/implemented for the REST-api. :smile:

**Comment by GideonZ** [comment]
No new features will be added to the socket dma. The socket dma is
deprecated and will disappear in 3.12.

In 3.11 there will be a proper http API, and a grace period for socket dma.


Op zo 2 apr. 2023 14:08 schreef Achim ***@***.***>:
