### ISSUE TITLE
File date is wrong.

### ISSUE THREAD

**Issue by Zibri** [GideonZ/1541ultimate#313]
If I save a file to unit 10 (which saves to my pendrive)
the file date is wrong.
I saved a few today and they appear with the wrong year (2022 instead of 2023).
Obviously the date in the ultimate 2+ menu is correct.

**Comment by Grrrolf** [comment]
Which firmware version are you using and which device? The Lattice or the old U2+?
Can you please sum up the exact steps (including each command) we need to follow to reproduce this?

**Comment by Zibri** [comment]
Ultimate 2+ fw 3.10a

To reproduce:
map the IEC (full fat32 pendrive) to device 10.
from C64 issue:
SAVE"TEST",10

Then from ftp, listing the files, TEST has 2022 date even if the U2 clock is 2023.

If instead I send a file using FTP to the U2+, the file has the correct date.

**Comment by radius75** [comment]
I was unable to reproduce this error.
It saved me the date and time correctly.
I saved the test PRG in USB Root, Temp and subfolders.
U2+ fw3.10a
Win7x64 FileZilla3.63.1 ftp client

Maybe something in U2+ configuration is crucial, or system specific, ftp client?

**Comment by radius75** [comment]
Are you saving this file with the command load"test",10 on a usb flash drive? And what if you connect the flash drive with this file directly to the PC, what date of creation/modification does it show?

**Comment by GideonZ** [comment]
Cannot reproduce.
