### ISSUE TITLE
Feature Request: please add support for .crt Blackbox V9 cartridge

### ISSUE THREAD

**Issue by radius75** [GideonZ/1541ultimate#314]
Hello.
Referring to the thread on FB: https://www.facebook.com/groups/ultimate64/permalink/10159897606797753/

Request to add support for Blackbox V9 .crt emulation
Two years ago BBv3,v4 and v8 were implemented. Thank you again for that :)

BB9 is a rare and legendary item in Poland :) The series of these cartridges dominated among users here.
And about the last version of V9, many only heard, but could not get it now.
The community of Commodore fans in Poland would be happy if they could run it with Ultimate.

Crt. BB9 can be run in the Vice emulator. 
You can prepare it from the .bin image using cartconv.exe (parameter -t bb9)

Some information and files:
[Black_Box_V9.0.zip](https://github.com/GideonZ/1541ultimate/files/11219869/Black_Box_V9.0.zip)
http://c64.com.pl/index.php/cartridge/rombit.html?cartridge=bb9
https://vice-emu.sourceforge.io/vice_17.html#SEC504

![obraz](https://user-images.githubusercontent.com/1929111/231699339-922ed4fa-f2dd-4c81-978a-7a8ec0952a44.png)

Will you need any additional information about this device?

Regards
Krzysztof

**Comment by GideonZ** [comment]
BlackBox V9 support has been added to 3.10f.
To be released shortly.

**Comment by radius75** [comment]
Wow. Great news. Thank you very much.

**Comment by sdsisdsi** [comment]
Thanks a lot :)
