### ISSUE TITLE
Feature request:  Settings save/restore

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#32]
From the FB group, just wanted to add this as a feature request.  Ability to load and save different configurations of the settings.  And i suppose flag one of them as the default configuration.

**Comment by Jumpman64** [comment]
Looks like this feature got already included since
Version 1.24 - Dated: 2019-10-13
- Added possibility to load / save and reset configuration settings

**Comment by GideonZ** [comment]
The one in Flash is the default indeed. And you can load / save configurations to a file and load them again, even strip them off unnecessary settings. So yes, this has been fully implemented.
