### ISSUE TITLE
U2+ configuration "load from file" is missing....

### ISSUE THREAD

**Issue by Zibri** [GideonZ/1541ultimate#322]
IN U2+ menu (pressing F5),
there is:
```
Save to Flash
Save to File
Reset from Flash
Reset to defaults
Clear Flash Config
```
IMHO there should also be a Reset from file.

```
Save to Flash
Save to File
Reset (or Load) from File
Reset from Flash
Reset to defaults
Clear Flash Config
```

**Comment by Zibri** [comment]
Oh nevermind... if I press CR on the config.cfg, it says Load Settings...
Confusing but it's ok..

**Comment by marty41** [comment]
Like with every other known extension too. ;) 
But this is no "reset", but loading a config file! 
The config file is text based and you can just put parts of the whole config into the config.cfg, leaving the rest of the config untouched!
