### ISSUE TITLE
Saving to U2+ from retroreplay monitor does not work.

### ISSUE THREAD

**Issue by Zibri** [GideonZ/1541ultimate#323]
To reproduce:
Use rr38pal.crt or action replay 7.5 pal as cartridge.
Switch off and on the c64.
press F3
You are not at the start screen of the C64.
Press the freeze button and press M.
Now from monitor save from $1000 to $CFFF to the u2+.

**Comment by Zibri** [comment]
From Retroreplay:
@10   (or @9)   works and the u2= answers with U64IEC ULTIMATE DOS V1.1
but then if I do S"test",10,1000,D000    I get device not present. (same happens with device 9)

**Comment by Zibri** [comment]
On action replay 7.5 pal instead the behaviour is this:
S"test",9,1000,d000
it writes: "SAVING TEST" and the hangs there indefinately.

**Comment by GideonZ** [comment]
This is a problem of the Action / Retro replay. The ROM does not check if it is a real drive and just uploads code and expects it to work.
