### ISSUE TITLE
Changing "IEC Drive and Printer" to Enabled freezes Ultimate2+ fw3.10f in the IEC menu

### ISSUE THREAD

**Issue by radius75** [GideonZ/1541ultimate#328]
-set IEC Drive and Printer to Enable
-Back: CRSR Left, or F8, or Run/Stop
-Freeze in the menu

Exiting via MenuButton, Enter menu and exiting  via "Reboot C64" does 
not activate IEC options and does not freeze. 
Even though the option is set to "Enabled".

Also in the F5 menu, Turn On Software IEC causes a freeze.

Related to FB thread: https://www.facebook.com/groups/ultimate64/permalink/10159930272347753/

**Comment by GideonZ** [comment]
Can reproduce this easily with the binary from the zip file in the download.
Cannot reproduce this with the binary that results from a clean build from
that EXACT SAME git hash.

This is highly peculiar.

I'll include some extra safety measures, such as:
* maximum loop count / auto disable when the IEC processor goes haywire
* a 'safe mode' like the U64 has, when the user keeps RESTORE pressed on
boot. E.g. keeping the left button of the cartridge pressed during boot.

**Comment by radius75** [comment]
FW3.10i fixed it
Thanks.
