### ISSUE TITLE
Drive code fails to upload to emulated drive

### ISSUE THREAD

**Issue by GameTimeWarp** [GideonZ/1541ultimate#347]
The following title, Leaps and Bounds! https://csdb.dk/release/?id=232144 uploads some code to the disk drive before the program starts which speeds up disk loading. It works as intended on a real 1541 drive but fails to upload the code on the UII+ .. The program crashes to BASIC after it attempts to upload the code to the emulated drive. Typing RUN after it crashes starts the program but it defaults to the stock KERNAL. Would be lovely to see this BUG? get fixed!

**Comment by johnlivdahl** [comment]
I tried this title on the U64 with the UII+ implementation integrated and it works the same as Vice (the same fast load is working on U64 and Vice).     You have some UII+ setting issue or an external IEC device connected.

**Comment by GameTimeWarp** [comment]
Doh, thanks johnlivdahl, somehow Software IEC was enabled on my UII+ ... disabled it and everything is working as intended
