### ISSUE TITLE
[SOLVED] fw3.10i - demo No Bounds, always hangs at the same moment

### ISSUE THREAD

**Issue by radius75** [GideonZ/1541ultimate#349]
I read this thread, so I did a test.
https://www.facebook.com/groups/ultimate64/permalink/10160008610527753/
https://csdb.dk/release/?id=232957

U2+, fw3.10i
Demo hangs every time at this point as pictured, fw3.10i
I tried, reset to default, clear flash, reinstal fw3.10i, still hangs.
Reverting to fw3.10f solves the problem. The demo plays to the end.
Another attempt to upgrade to fw3.10i and it still hangs.

![349384152_565712812432135_5108868177076483962_n](https://github.com/GideonZ/1541ultimate/assets/1929111/87de611d-f8ca-4df2-8f2f-65f0eac32b0c)
![349622429_249711811088222_570390049924203680_n](https://github.com/GideonZ/1541ultimate/assets/1929111/e17c96c4-df0d-45ce-97fd-a1d1debf4552)
![349538615_632915798892737_2607270928450902309_n](https://github.com/GideonZ/1541ultimate/assets/1929111/5bb37e9b-7932-4e8a-ad4d-7954c71c881d)

**Comment by GideonZ** [comment]
Very interesting. There are no differences in drive emulation between these two versions, especially not on U2+.

**Comment by radius75** [comment]
False alarm.
I tested U2+ with fw3.10i, disconnected from expansion port C64.
External PSU 5V/2.5A.
The whole demo played to the end!

I cleaned the u2+ edge connector and the expansion port,
now everything works fine.

The confusing thing was that hang was only present on 3.10i at the same time. Apparently, at that time, the power consumption is higher.
