### ISSUE TITLE
Feature request: Custom Character ROM and BASIC ROM on 1541U

### ISSUE THREAD

**Issue by Korbaux** [GideonZ/1541ultimate#359]
Forgive me if this has been suggested before, but could there, if possible, be an option to use a custom character ROM or BASIC ROM on the 1541U?

**Comment by mrdudz** [comment]
That can not be done on the cartridge port, i think (even Kernal involves a lot of black magic trickery)

**Comment by Korbaux** [comment]
Oh ok!
