### ISSUE TITLE
Disk set as Drive 9, RUN causes LOAD":*",8,1

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#36]
I have a disk as 9, and 10 is disabled.  When selecting a d64 image, then RUN, it unfreezes, but sends LOAD":*",8,1 instead of 9,1.  Minor issue, but just thought you might want to know.

**Comment by GideonZ** [comment]
"DMA load mimics bus ID" setting can be used to change this behavior...

**Comment by xlar54** [comment]
Ok thanks Gideon, sorry for the issue

**Comment by GideonZ** [comment]
No problem! Good question for FAQ.
