### ISSUE TITLE
Probably a TYPO in tape timings...

### ISSUE THREAD

**Issue by Zibri** [GideonZ/1541ultimate#361]
C64 PAL speed is 985248 cycles per second.

In file: 
I read:
```
architecture arch of tape_speed_control is
    constant c_pdm_target_pal       : natural := ( 985250 * 512) / (g_clock_freq / 128);  
    constant c_pdm_target_avg       : natural := (1000000 * 512) / (g_clock_freq / 128);  
    constant c_pdm_target_ntsc      : natural := (1022727 * 512) / (g_clock_freq / 128);  
```
Please correct to 985248.

NTSC clock is correct.

**Comment by GideonZ** [comment]
It is irrelevant.

For 50 MHz systems, c_pdm_target_pal  evaluates to 1291, regardless whether the value is 985250 or 985248.
For 62.5 MHz systems (U2+), c_pdm_target_pal  evaluates to 1033, regardless whether the value is 985250 or 985248.
For 66.6 MHz systems (U64), c_pdm_target_pal  evaluates to 968, regardless whether the value is 985250 or 985248.

In all cases the divider value is high enough to reach approx 0.1% accuracy, which is more than enough for tape emulation.

**Comment by Zibri** [comment]
It might seem irrelevant to you, but my program WORKS on Mister and Cute32 but not on U2 because of THIS error.
Just put the right value! **985248 is the right value.**

**Comment by GideonZ** [comment]
I can change the value, but it doesn't make any difference, as I pointed
out in detail.Message ID: ***@***.***
.com>

>
