### ISSUE TITLE
Some .crt cartridge images don't work properly on U64

### ISSUE THREAD

**Issue by Jusalak** [GideonZ/1541ultimate#377]
Jupiter Lander and Radar Rat Race .crt images don't work properly on U64, they run in a way and there is sound, but display is garbage. Firmware V1.42 - 3.10j.

These .crt files work fine on VICE. Real physical cartridges of both of these work fine on U64.

**Comment by Jumpman64** [comment]
Both .crt images of these games do work (via "Run Cart") on U64 Firmware V1.43 - 3.11

**Comment by GideonZ** [comment]
More or less the same issue as the solid bars in Power Cartridge. Solved in 3.11.
