### ISSUE TITLE
U64 3.11 (11E) Streams can't be opened over WiFi only

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/1541ultimate#395]
Cannot get streams to work with U64 Streamer with ONLY Wifi enabled on U64 ? Wifi in itself works perfectly (I can ftp or telnet to U64) but for streams to work I need to have wired LAN enabled... over wifi I cannot enable streams in the F5 menu on U64 at all, I get an error "No (valid) link" when I want to enable the streams ... as soon as I connect the LAN cable I can enable the streams.

Note that if I have BOTH LAN and WIFI enabled I can use U64 Streamer with both IP-s on LAN and WIFI, so it seems it is only actually enabling them in F5 Streams menu that doesn't want to work.

**Comment by TomCat666** [comment]
Sorry. I have just seen this in the documentation: The WiFi cannot be used for streaming video and audio. This is only available on the LAN port. Closing

**Comment by VanessaE** [comment]
Hah, nah, I can barely grok simple RLE.  I'll leave video stuff to the people who know wtf they're doing.  🙂

**Comment by xinteksik** [comment]
Some use cases only involve creating a screenshot, and in those cases the speed over Wi-Fi might be sufficient. Or is there another way to take a screenshot already now?
