### ISSUE TITLE
Ultimate II+L issues 3.11 (11e)

### ISSUE THREAD

**Issue by THE-MrMicro** [GideonZ/1541ultimate#397]
I noticed Ulticopy just freezes and never accesses an external device. I have to physically reset the 64 to recover. No buttons on the 1541U2+L are responsive.

I tried it with my 1541 U2+ (3.10a) (11c) and it works no problem. I haven't upgraded my original to 3.11, so I can't test if it's a FW issue or just a known 'bug' with the 1541U2+L. Thought I'd post here first.

I'm using a shortboard 64c and have a CMD HDD, 1541-II and a 1581 connected to it, but again, Ulticopy works no problem with the 1541U2+

Thanks in advance!

Best,
J

**Comment by THE-MrMicro** [comment]
Update: I reverted the 1541U2+L back to 3.10j (11d) and Ulti-Copy works as expected.

However, after upgrading BACK to 3.11 (11e), Ulti-Copy freezes the system and a physical reset is required.

So apparently an error with the latest FW.

**Comment by GideonZ** [comment]
It is a known issue. You can use UltiCopy by manually turning off the internal drives, I think. (The bug is that I tested UltiCopy with the internal drives and forgot to turn them off again when starting UltiCopy.)

**Comment by THE-MrMicro** [comment]
Yes, that worked with the drives off...

I was looking for a 'blurb' about this being a known issue, but couldn't find anything, so just posted here..

ThanX G!
