### ISSUE TITLE
U2+L - I was testing out Drive and Kernel ROMs but now just get blank screens and unable to access any menu

### ISSUE THREAD

**Issue by Gun-neR** [GideonZ/1541ultimate#398]
I was testing out JIFFYDOS kernel ROMs on my C128 (have never used it before and was just loading various ROM's in a trial and error method)... but all I got was the error :(  And after the drive loading sounds just kept playing for a about a minute, without any other action, I rebooted the C128... 

But now upon power-up all I get is a brief "spinning drive sound" and blank screens (I am running dual monitors for 40-80 col) and unable to access any menu!!  Removing the U2+L lets the C128 boot normally, so that is OK still.

I am at a loss... according to the documentation, the "Recovery Mode" (pressing middle button while powering up) is NOT for the UII-L (which I have)... and sure enough, nothing happens when I try.  In fact no combination of buttons and/or rebooting seems to do a thing.

Any ideas??

**Comment by Gun-neR** [comment]
UPDATE:

I moved the U2+L to my SX-64, and at least it boots to show:

JIFFIDOS V6.01 (C)1989 CMD
C-64 BASIC V2 38911 BASIC BYTES FREE
READY.
_

So apparently I was able to load a kernel after all... for all the good it does me :)  Unfortunately, pressing the menu button just shows a scrambled screen (probably due the SX-64??).  Unfortunately, I am totally unable to navigate around to "restore" the kernal, or whatever I need to to do...

![2024-02-12 22 18 07](https://github.com/GideonZ/1541ultimate/assets/28169425/c4742c07-0157-421f-9728-e0c5b71181b3)

**Comment by johnlivdahl** [comment]
C128 doesn't allow a cart to inject kernal ROMs (that only works on the c64).   You can use telnet to change the settings to disable the jiffy dos kernal ROM.

**Comment by Gun-neR** [comment]
Another crappy update:

In a supposed lightbulb moment, I figured that "updating" the firmware would restore everything.  So using a blank thumb drive with only **update.u2l** on it, I was able to use my limited "muscle memory" to navigate to that file and run it...

And it did... something?... then blanked out the screen and never recovered...  

Now it is effectively "dead" on all my available commodore units :(

**Comment by Gun-neR** [comment]
> You can use telnet to change the settings to disable the jiffy dos kernal ROM.

Um... I am just a new U2+L user and haven't much of a clue what you just said :P  How can I do anything without access to the menus?

**Comment by johnlivdahl** [comment]
Telnet connects via the network.   So run a telnet program on your PC like "Putty" and connect to the IP address of your Uii+L   You can use the web interface of your router to find the IP address of UII+L

**Comment by Gun-neR** [comment]
@johnlivdahl Thanks... I was just going through the manual about telnet, and realized what you then said.

However, on a whim, I moved the U2+L back to the C128 (still blank screen) and then back again to the SX-64... and this time it loaded back up to the JIFFYDOS screen again.  

I am guessing I am running into yet another quirk of the SX-64 that I have also realized with a KungFuFlash cart.

Anyhow, I tried again with the "muscle memory" action, but this time it did something, differently??? with additional stuff happening on the unreadable screen... And after it finished whatever it was doing, it just stayed static (no automatic reboot).  I left it for a bit, then manually rebooted the SX-64...  BACK TO NORMAL!!  And also on the C128 :)

OK, lessons learned...  Both of my Commodores (SX-64 and C128) have quirks with this cartridge that make exploring the full features of this U2+L... well, lets it call it... exciting :)

**Comment by tracta67** [comment]
I justed bumbed into the same issue on my C128. Blank screen. 
Can anybody please explain to me how to use telnet to change the settings to disable the jiffy dos kernal ROM ? 
I have never used telnet before. 
Thanks a lot!

**Comment by radius75** [comment]
You need some terminal program.
You must be on the same subnet as your Ultimate2 - logged into the same router.
For example, a terminal program for a phone with AndroidOS.
The standard hostname is Ultimate-II.
![Screenshot_20240308_074551_ConnectBot](https://github.com/GideonZ/1541ultimate/assets/1929111/4a382715-f247-4fa2-a63e-d0c0b48a46dd)
![Screenshot_20240308_074222_ConnectBot](https://github.com/GideonZ/1541ultimate/assets/1929111/6602d383-d065-4793-bde2-033e0a33ab7a)

**Comment by radius75** [comment]
![Uploading Screenshot_20240308_075812_ConnectBot.jpg…]()

**Comment by radius75** [comment]
![Uploading Screenshot_20240308_080053_ConnectBot.jpg…]()

**Comment by radius75** [comment]
If for some reason it refuses to connect via hostname, then you will need to enter the IP address of the Ultimate instead.

**Comment by tracta67** [comment]
Dear Gideon,

 

Thanks a lot for the quick reply. I’ll try this tonight. 

 

It might be worth saying on the website to avoid Jiffydos, especially for the people with Commodores 128. 

 

Best,

 

De : radius75 ***@***.***>
Répondre à : GideonZ/1541ultimate ***@***.***>
Date : vendredi 8 mars 2024 à 08:44
À : GideonZ/1541ultimate ***@***.***>
Cc : tracta67 ***@***.***>, Comment ***@***.***>
Objet : Re: [GideonZ/1541ultimate] U2+L - I was testing out Drive and Kernel ROMs but now just get blank screens and unable to access any menu (Issue #398)

 

If for some reason it refuses to connect via hostname, then you will need to enter the IP address of the Ultimate instead.

**Comment by tracta67** [comment]
Thanks a lot. It was frightning but thanks to this I was able to save my date. 

 

All the best,

 

 

De : radius75 ***@***.***>
Répondre à : GideonZ/1541ultimate ***@***.***>
Date : vendredi 8 mars 2024 à 08:21
À : GideonZ/1541ultimate ***@***.***>
Cc : tracta67 ***@***.***>, Comment ***@***.***>
Objet : Re: [GideonZ/1541ultimate] U2+L - I was testing out Drive and Kernel ROMs but now just get blank screens and unable to access any menu (Issue #398)

 

Screenshot_20240308_081930_ConnectBot.jpg (view on web)
Screenshot_20240308_080053_ConnectBot.jpg (view on web)
