### ISSUE TITLE
u64: super bread box 64k crashes at start up when jiffyDOS kernal is loaded

### ISSUE THREAD

**Issue by thomasf** [GideonZ/1541ultimate#40]
The games start up image is shown but nothing else happens after that.

$ shasum SBB64K.crt
9cf83f7402fe01a107b839472a6d42e609b29aff SBB64K.crt

download game here (free) http://rgcd.bigcartel.com/product/super-bread-box-commodore-64

The same .crt + jiffydos roms works well with 1541u2+ and c64 reloaded mk2

**Comment by xlar54** [comment]
thomasf - can you check with the latest (1.2) U64 update?  Lots of things fixed, and this game appears to require purchase in order to test.

**Comment by thomasf** [comment]
it's a free download, payment is optional. I don't have access to my U64 atm.. I'll try to remember this

**Comment by mikebetz42** [comment]
You can download it for free at: <https://rgcddev.itch.io/super-bread-box> https://rgcddev.itch.io/super-bread-box/download/eyJleHBpcmVzIjoxNTYxMTM2Mjg2LCJpZCI6MTc0MDB9.97DL5eWjiNvOfDizGoepZhIPO0c%3d

-Mike

________________________________

**Comment by thomasf** [comment]
I think it might have started working now since I updated to the latest firmware 1.24 version but I need to verify that jiffydos is working correctly first because it might not be unless I am missing some new setting.. I can probably verify some more during the weekend.

**Comment by thomasf** [comment]
seems to work now
