### ISSUE TITLE
1541U2+ Issues.. 

### ISSUE THREAD

**Issue by THE-MrMicro** [GideonZ/1541ultimate#418]
So my U2+ today developed a bunch of symptoms out of nowhere.

1. Drive sounds stopped working. Despite being enabled, internal speaker turned up to 15 and default files being used
2. No mounting of d64's
3. ?DEVICE NOT PRESENT ERROR (tried new cable and making only drive on IEC chain AND disabling Drive B) after mounting.
4. Re-Flashing does not clear settings or make a difference, despite Formatting FLASH and Flashing Runtime. All original settings are still there.
5. Carts work as expected. DMA loads work as well as EMUSID's. Interal 6581 worlds as well
6. Alternate Kernel does not work AFTER re-flash, despite _**still being shown as file**_. Will work as expected after setting a file as Alternate Kernel again.
7. Tested Commodore 64 for potential issues. All diagnostics passed AND C=64 works perfectly with my other 1541U2(L)
8. Was constantly asking to change the default drive to 1541, when loading d64's, despite Drive A already being set for 1541.

This problem stated AFTER I flashed to 3.11. I've tried re-flashing 3.11 and all the way back to 3.10a, to 3.10j and nothing is getting it to work. 

Is there an internal reset or something I can do to wipe everything?

Oh I also tried different thumb drives to no avail. I use SanDisk 8-16gb thumb drives.

Any advice is helpful! Thanks much!

Best,
Mr.Micro

**Comment by THE-MrMicro** [comment]
On a follow-up, the thumbdrive is getting EXTREMELY hot. I noticed when pulling it out... May be normal, but don't recall actually noticing it..

**Comment by THE-MrMicro** [comment]
So here's the deal, my U2+ partially bricks with the issues outlined in the OP. I have been able to get it to work as expected by flashing back from 3.4, 3.6 to 3.7 to 3.9 and that's it.

3.10, 3.10a, 3.10j or 3.11 simply DO NOT work...

I've done a power cycle while holding middle button and that doesn't help and I also tried the other USB port and that does nothing either.

**Comment by radius75** [comment]
Try a different flash drive. A high temperature may mean that it is drawing a lot of current.
After updating to 3.11, did roms and sound files of the floppy disk drive appear automatically in the flash/roms folder?

**Comment by THE-MrMicro** [comment]
I did try multiple flash drives.. The one I was using is the one from Gideon, not sure brand, but its a 'flippy' and says Ultimate 1541 (or something similar), but since it's the original I tried the one working in my 1541-L and also tried a brand new SanDisk.

I think the heat is nothing, it was hot pulling from my USB hub too..

I'll have to double check the sound and ROM files though.. I knew the drive sounds went there, but  I either forgot or didn't realize the ROM files went there too.. I thought you associate them under DRIVE A/B and they 'pull' from that file location.

I'll double check and report back.. thanks.. Keep in mind it's not just 3.11, the problem starts with 3.10..

Thanks for response.

**Comment by THE-MrMicro** [comment]
So the ROM and sound files WERE there in the flash/ROMs folder.

However, when simply just re-selecting them and setting them as drive ROM, it started working again. 

It's weird, it was the same with the Alt Kernel ROM, it showed it was set as JD, but it wasn't loading it, until I just reset it. 

I see now though with the drive ROMs, the standard 1541/71/81 ROMs are in the flash/roms folder, but alternate ROMs, AFTER being set are copied to that location as well AND NOT pulled from the file location, so despite showing the ROM as set, THAT ALTERNATE ROM was not there after the flash.. interesting..

Thanks again.. You were a big  help. 

I will close this ticket
