### ISSUE TITLE
USB keyboard - use the extra keys

### ISSUE THREAD

**Issue by BacchusFLT** [GideonZ/1541ultimate#43]
An external USB keyboard has multiple additional keys over the native C64 keyboard (most notably the F9 to F12). As I find it somewhat inconvenient to dive in and press the power button hundred times per day, I would like to suggest that the feature reset, trigger menu and cartridge freeze are mapped to these accessible keys.

**Comment by GideonZ** [comment]
F10 is already mapped to entering the menu.
Reset can be performed by pressing four control keys at one side of the keyboard (I think the left side)
Freeze is not yet implemented, indeed....

**Comment by BacchusFLT** [comment]
The idea is still to never have to dive in for that little button. And
there are F keys that are surely not needed for the host environment that
could be used.

**Comment by Jumpman64** [comment]
Oh, your issue is older. There's another one regarding this topic
https://github.com/GideonZ/1541ultimate/issues/125
how do we merge these? :)

**Comment by GideonZ** [comment]
Reset: All 4 modifier keys on the left
Freeze: F11
Menu: F10 / Scroll Lock
