### ISSUE TITLE
[U2L] C128 Cartridge issue with "Prince of Persia"

### ISSUE THREAD

**Issue by Flexmaen** [GideonZ/1541ultimate#431]
I tried these releases:
https://csdb.dk/release/?id=102540
https://csdb.dk/release/?id=102434

They worked fine on the C64 but didn't work on any of my C128s.
Same problem on the new Ultimate 2+L as on the older 1541 Ultimate II.

**Comment by Grrrolf** [comment]
Does it work using a real easyflash cartridge and your C128?

**Comment by Flexmaen** [comment]
> Does it work using a real easyflash cartridge and your C128?

Yes.

I do not have the EasyFlash my self, but some one confirmed me that it runs and the C128 with the EasyFlash.
Also the game seems to use 2Mhz in the frame on a C128 which means that it also was tested on a C128.

**Comment by GideonZ** [comment]
Did you turn on the forced 2 MHz mode in the C64 and Cartridge settings?

**Comment by Flexmaen** [comment]
No. I turned it on and tried again, and **it works** now!

Thank you!
But how to figure out these things? Is there any disadvantage? Should there be some C128 default settings?

**Comment by Grrrolf** [comment]
Now your issue has been solved, don't forget to close this issue.
