### ISSUE TITLE
wifi firmware addition failure

### ISSUE THREAD

**Issue by leeuwtjex** [GideonZ/1541ultimate#434]
Wifi module programming by using the espc3_v1.1.esp file returns:  "ESP32 Program Failed"

After upgrading my Ultimate-II Plus-L 3.11a  (11F)   Gideon cartridge,
installing the wifi firmware file returns above error.
The steps I have taken:

1. Upgraded the firmware by this update :
    https://github.com/GideonZ/ultimate_releases/raw/master/u2pl_3.11a.zip   

2. install the new firmware by simply selecting it in the ultimate gui on the c64.
   It asked me to shutdown the c64 at end.  I restarted.  Great! Now i have a basic editor,  ultimate http webserver  and wifi   
   included on my c64,  WOW !  

3. Trying the wifi module I found I needed to run the file above: espc3_v1.1.esp.
   After a few seconds:  "ESP32 Program Failed"

End.

What needs to be done here to have WIFI module be able to 'talk' ?

Thanks in advance.

**Comment by GideonZ** [comment]
Could you include a picture of the WiFi module?

**Comment by GideonZ** [comment]
@leeuwtjex Could you include a picture of the WiFi module, for a proper reply to your issue?

**Comment by leeuwtjex** [comment]
Ha Gideon. I don't have a wifi module. Only a 1541ultimate2 cartridge. Isn't the wifi module 
on the cartridge board by default? Maybe I misunderstood the wifi concept for your cartridge design.
