### ISSUE TITLE
DMA bus drive quirkiness

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#49]
The basics of this one is that I have a program which tries to load a config file from the device which loaded the program.  Ive set the DMA Mimics Device ID: 11.  And the virtual drive is 11.  But when I select RUN from the menu to execute the program, it locks up trying to read the config file.

The program knows the device id properly.  So something is weird with maybe initializing the drive.  The only way I can really give you more info on this one (without making you read my code) would be to put together a youtube video demonstrating the issue.  Let me know if you need that or if this makes sense.  Im working on an update to the terminal program that will read from a phonebook, and most people will probably be selecting it and RUN directly from the U64 menu.  I could force them to use a D64 image of it, if thats the only workaround right now. (which works as expected).

**Comment by GideonZ** [comment]
The 1541 needs time to initialize after reset. Have you taken this time into account?

**Comment by xlar54** [comment]
I think this issue is outdated and cant do much to reproduce, so closing
