### ISSUE TITLE
Virtual drive - going into D64 images giving zero for all file sizes

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#50]
Ive tracked this down to iec_channel.h:

`   int read_dir_entry(void)

    {

        if(dir_index >= dir_last) {

            buffer[2] = 9999 & 255;

            buffer[3] = 9999 >> 8;

            memcpy(&buffer[4], "BLOCKS FREE.             \0\0\0", 28);

            last_byte = 31;

            pointer = 0;

            prefetch_max = 31;

            prefetch = 0;

            return 0;

        }

        printf("Dir index = %d %s\n", dir_index, (*interface->iecNames)[dir_index]);

        FileInfo *info = (*interface->dirlist)[dir_index];

        //printf("info = %p\n", info);

        uint32_t size = 0;

        uint32_t size2 = 0;

        if(info) {

            size = info->size;

        }

        size /= 254;  <-----------------------------this line

        if(size > 9999)

            size = 9999;

        size2 = size;`

When that line is as-is, VFS file sizes are correct, but when you cd into a D64 image, they report zero for all files.  Commenting that line out, gives proper file sizes inside D64 images, but incorrect sizes in the regular VFS.  Catch-22 or am i reading this wrong?

**Comment by xlar54** [comment]
this seems to help, but i dont want to submit a pull request because im not exactly sure how this should work:

if (size > 254)
            size /= 254;

**Comment by xlar54** [comment]
also, should be able to do away with the 9999 BLOCKS FREE as well from inside a disk image.

**Comment by GideonZ** [comment]
Dear xlar,
Thank you very much for your contributions. Yes, please fork and issue a pull request. This is the standard GIT way of working. It also allows me to review the changes and maybe give some pointers when needed. Some changes may go against an established design pattern, and reviews are a great mechanism to achieve maintainable code and avoid quick hacks in the main stream code. (I am not claiming that I have not added any hacks myself.. ;-) )

**Comment by GideonZ** [comment]
> this seems to fix the issue, but i dont want to submit a pull request because im not exactly sure how this should work:
> 
> if (size > 254)
> size /= 254;

As Markus pointed out, this won't work. This kind of code is in the category "hacks". :-)

**Comment by xlar54** [comment]
Yep, no problem.  Will try to come up with a better solution.
