### ISSUE TITLE
Built in SID player :  Add support for .mus file format (Compute Sidplayer)

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#53]

**Comment by xlar54** [comment]
Another popular format.  Would love to see this added.

**Comment by xlar54** [comment]
https://github.com/xlar54/mus-player  if any of this helps.  It was lifted from the ML included on the book's disk

**Comment by WilfredC64** [comment]
MUS file support (including stereo MUS files) has been implemented now and will be included in the coming firmware update.

**Comment by xlar54** [comment]
Nice!

**Comment by xlar54** [comment]
closing this issue as Wilfreds updates have been merged
