### ISSUE TITLE
Built in SID player : Does not work here with alternate Kernel active

### ISSUE THREAD

**Issue by michas0602** [GideonZ/1541ultimate#54]
As written, the built in SID player (U2) does not work here when I have my JiffyDOS active.

**Comment by xlar54** [comment]
Works for me with JiffyDOS enabled.  (U64)  I cant do alt kernal on my UII+ because its in a 128.  If that helps in debugging.

**Comment by marty41** [comment]
Does also work fine for me, with my 250407 board equipped with SuperKernal and JiffyDos, JaffyDos, ProfessionalDos or SpeedDos activated. (1541 Ultimate 2) Tested with firmware 3.2 and also with 3.3.

**Comment by michas0602** [comment]
Thats strange...but why doesnt it work here? I´ve tested it several times - when I activate a c64kernal.bin, the internal SID-player just shows a blackscreen...if I disable alternate Kernal it works fine...

I´ll do further tests with other kernals and different settings tomorrow...but thanks already for your feedback

**Comment by GideonZ** [comment]
Closing this ticket, because it seems to work for others.
