### ISSUE TITLE
included FC III does not work

### ISSUE THREAD

**Issue by Flexmaen** [GideonZ/1541ultimate#57]
The Final Cartridge III that is included in Firmware 3.2 does not work correctly.

It is not possible to get the blue desktop ([like here](http://www.64er-online.de/museum/images/fc3.jpg)).
I did try another FC III CRT-file I found somewhere and that works fine.

Tested on my C128 and C64 with the PHI2 value that works without problems for other cartridges (and fpr the other FC III image too).

**Comment by Grrrolf** [comment]
Which Ultimate cartridge are you referring to? The 1541 Ultimate-II or the Ultimate-II Plus? 
Type "DESKTOP" in basic to enter the desktop. The included FCII was hacked (for a long time already) so that it bypasses the DESKTOP and enters BASCI directly.

**Comment by marty41** [comment]
> Type "DESKTOP" in basic to enter the desktop. The included FCII was hacked (for a long time already) so that it bypasses the DESKTOP and enters BASCI directly.

@Flexmaen: and the way @Grrrolf explained, is the way it is expected to work on the U2(+) /U64. ;) So also no issue.

**Comment by Flexmaen** [comment]
Ah ok sorry. I tried to get there by chosing "desktop" via freezer, which will just get the basic screen.
Also I did not find the solution for this in the FAQs and thougt it was broken since I think it worked like expected with an older version.
