### ISSUE TITLE
Please update build instructions for U64

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#59]
when doing:

make u64

I get the following:

Making all requires output, result and result/ultimate.app result/ultimate.elf output/ultimate.sim
make[1]: Leaving directory '/home/scott/1541ultimate/target/software/nios2_u64'
make[1]: Entering directory '/home/scott/1541ultimate/target/software/nios2_update_u64a4'
make[1]: *** No rule to make target 'u64.sof', needed by 'output/u64.pof'.  Stop.
make[1]: Leaving directory '/home/scott/1541ultimate/target/software/nios2_update_u64a4'
Makefile:179: recipe for target 'u64' failed

**Comment by xlar54** [comment]
Normally Ive been only building for the u2plus (which is "make u2plus", then "make niosapps").  So looking for the analogue to build the u64 code as well.  comes close, but this error above stops it.

**Comment by xlar54** [comment]
Ive been using Altera Quartus 15.1 Lite as described, along with gcc 7.3.0

**Comment by markusC64** [comment]
That's clear, because the public source code does NOT contain the fpga for the Ultimate 64.
1st, you have to get the fpga blob. You cannot build U64 out of the box.

**Comment by markusC64** [comment]
Correct setting. The FPGA is missing. Either you get the .sof file from Gideon (best choice for building 'git master' - or you extract an fpga blob from an Ultimate 64 - in that case you have to patch the Makefiles not to generate that blob frorm the .sof (Problem: Does not fit to development application of 'git master').

**Comment by thomasf** [comment]
thats bad :( why not?

**Comment by xlar54** [comment]
Gideon, can I get the .sof file?  Im not sure how to extract it from a U64.  Or will there be plans to make it public also at some point?

**Comment by xlar54** [comment]
MarkusC64 - do you know of a method to extract the FPGA blob as mentioned above?  If not, then it seems I should close this issue until Gideon decides to push the U64 code out there.

**Comment by markusC64** [comment]
You should have a private message.

**Comment by xlar54** [comment]
As of today, the sof file has been added to /external/u64.sof

make u64 still failed on me though because it couldnt find the file.   Changing u64.cof to:

<sof_filemame>/home/scott/1541ultimate/external/u64.sof</sof_filename>

temporarily fixed the issue.  Build worked fine.  Ill try to figure out how that path is set up and submit a pull request (unless it something local to Gideon at the moment)

**Comment by GideonZ** [comment]
Oh okay.. that actually makes sense. Not sure if you can do an export of the variable and use it in the XML file (what the .cof file basically is). Probably not. But what could be done is make the .cof file a target by itself, and build it up from a template and to the string replacement with _sed_.  If you put this together in a pull-request, that would be good. In the .cof file you can see where I keep my U64 files ;-)

**Comment by GideonZ** [comment]
The FPGA image is added to the public repository.
