### ISSUE TITLE
Rare u2+ menu screen corruption

### ISSUE THREAD

**Issue by sneakernets** [GideonZ/1541ultimate#64]
NOTE: This might be due to voltage dips!

I have an NTSC "slim breadbin" from around the end of 1986 with a UP9600 modem installed. Very rarely, pressing the menu button brings me to the menu, but all the text will be a pink, garbled mess. Going back to the basic prompt from here slices off the first usable column of text on the left side, and (even rarer) switches video modes to make the BASIC prompt look like pea soup. In Final Cart III mode, a purple mess replaces the cursor on the menu screen...

Not sure what's going on here. I've cleaned the contacts on all ports, the cart slots, and more, but it seems to be graphical corruption more than anything else.  Switching the C64 off and back on again usually fixes the issue. I'm going to be checking the caps on my board to see if there are any failing ones that only get fussy when that much power is being drawn through from all the attachments.

**Comment by GideonZ** [comment]
You may try to fix this by turning OFF the PHI2 edge recovery, or increase the Addr valid timing by one tick.

**Comment by sneakernets** [comment]
I will try that tonight and let you know.

**Comment by Grrrolf** [comment]
@sneakernets, can we assume this issue has been solved for you?
If so, this ticket can be closed.

**Comment by sneakernets** [comment]
yeah, this has been solved.
