### ISSUE TITLE
Utilize sd2iec for VFS if compatible

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#65]
https://sd2iec.de/

various cloned repos: 

https://github.com/rkrajnc/sd2iec

https://github.com/Larswad/sd2iec_mega2560

https://github.com/Ghouli/sd2iec

**Comment by GideonZ** [comment]
Not compatible enough... Some commands have been added, though, and some bugs were fixed. There are now commands to support partitions. Also the standard commands "copy", "scratch", "rename", etc now work, as well as reading from the SoftwareIEC through a data channel. M-R and M-W are implemented, but just write to a "blind" piece of RAM. Obviously M-E does not work, and neither do all the block commands.

**Comment by xlar54** [comment]
These additions will make the VFS much more usable.  Thanks!
