### ISSUE TITLE
U64 Trilogic V3.2 frozen programs

### ISSUE THREAD

**Issue by RichardTND** [GideonZ/1541ultimate#68]
C64 games and other programs frozen with Trilogic V3.2(and possibly higher) Expert Cartridge fail to run on the Ultimate 64. After loading the programs normally, the screen crashes and shows plain garbage, doing nothing else. This event also occurs on the current version of the cartridge. Two examples of Public Domain
games used this freezer. One used V3.1 and the other used V3.2. V3.1 works.

[Trilogic_Freezer_Test.zip](https://github.com/GideonZ/1541ultimate/files/2974986/Trilogic_Freezer_Test.zip)

**Comment by GideonZ** [comment]
Fixed. Was caused by a spurious NMI interrupt, caused by a false interrupt event in the 6526. Thanks to David Horrocks for pointing me into this direction.  (The public release in which this is fixed will be 1.18..)
