### ISSUE TITLE
[U64/U2 V3.0.417 to V3.4c] Extract a file from a T64-Image

### ISSUE THREAD

**Issue by t-h-e-joker** [GideonZ/1541ultimate#76]
If I copy a file with <C=>+<C> inside a T64-image and paste it outside with <C=>+<V>, then a window "Copying..." appears and do not react anymore. 
The same operation with images like D64 / D71 / D81 work correctly.

Attached is the zipped file exolon.t64

[exolon.zip](https://github.com/GideonZ/1541ultimate/files/3127763/exolon.zip)

**Comment by t-h-e-joker** [comment]
Works with firmware 1.20/1.21 on the U64.

To be on the safe side we should wait for the new firmware for U2(+) before closing this issue.

**Comment by GideonZ** [comment]
This has been fixed indeed. It will appear in 3.5 when released for U2+.

**Comment by t-h-e-joker** [comment]
Works fine in 3.6 (114) with the U2.
