### ISSUE TITLE
QUESTION: How / where in the code does it do a RUN (not DMA)

### ISSUE THREAD

**Issue by xlar54** [GideonZ/1541ultimate#93]
I checked the GEOS code, and it runs a BASIC program by putting an interrupt in that waits for a short period of time and then writes LOAD...,,x,1 on screen with CR in buffer.  Then jmps to BASIC.  The interrupt does its work then unloads itself.  Is this how you are doing it also?  Could you point me in the right direction to look at it?

**Comment by GideonZ** [comment]
It is part of the bootcrt.tas :-)
