### ISSUE TITLE
Problems with tape loaders: S-LOAD, and FLIMBO'S QUEST

### ISSUE THREAD

**Issue by RichardTND** [GideonZ/1541ultimate#94]
Only a couple of issues for me to point out, which occurs in current (1.20) and previous firmware built for the Ultimate 64. (Now using V1.22)

The first one is the game Gryphon by Quiksilva. This event seems to occur on every version I tried to play so far. The front end runs okay, but after pressing fire on the game. It crashes.

Secondly, the .D64 and .TAP original version of Flimbo's Quest fails to run the IRQ loader, which should display a loading picture with music. Instead, I a plain black screen.

**Comment by t-h-e-joker** [comment]
Set cartridge to "None" and gryphon will run!

**Comment by Jumpman64** [comment]
Please name the D64 and TAP version you're referring to.
e.g. https://csdb.dk/search/?seinsel=all&search=flimbo%27+quest&Go.x=0&Go.y=0

**Comment by RichardTND** [comment]
Okay. Gryphon works. As for Flimbo's Quest, that doesn't. I cannot remember where I had it from, although I do have the original physical tape copy. I think it may have been C64games.de

The problem I get is after loading finished on side 1 of the .tap, instead of running the loading picture and music (Like VICE does), the screen is black and freezes. 

http://c64games.de/phpseiten/spieledetail.php?filnummer=1617

**Comment by Jumpman64** [comment]
Both D64 versions and the TAP version (unprotected & trainer) included in the zip file on c64games.de do work. They don't contain an IRQ loader routine. Loading continues directly after pressing the button at the title picture.
You see, it's important to specify the version. Isn't there any intro in your D64 version?

**Comment by RichardTND** [comment]
The .D64 trainer releases work. The .tap still hangs, and blacks out instead of display the loading picture. In VICE it works. Usually if loading errors occurred the border would go red. It didn't here. Try this .tap and see if it still works on your U64:
[fq.zip](https://github.com/GideonZ/1541ultimate/files/3319994/fq.zip)

**Comment by Jumpman64** [comment]
I can confirm that the attached .tap file loads on emulators, such as BMC64 and Hoxs64, but fails at/before Flimbo's Quest loading screen picture on the U64 rev1.2/fw1.21/3.5a with original ROM set. It ends with a black screen as RichardTND reported. 
Might be something similar related to an IRQ loading routine? As there's some inconsistence with the "bad apple demo" that uses IRQ loading too.

Other .TAP file thing: i didn't see the functions "Rewind tape" and "Stop tape". Is that an automatic thing?
While testing around the LED on the USB stick was still continue flashing after a reset. I guess a tape stop would be good? After turning the cassette a rewind would be needed.

(Don't know about the protection of FQ but the workaround for Freeload mentioned in the FB group didn't help: loading some other prg ahead to fill up the C64 memory randomly, doing a reset and then loading the tape.)

**Comment by GideonZ** [comment]
There is a stop tape command in the F5 menu.

**Comment by RichardTND** [comment]
Other tape loading issues of .tap files (Which may be the same type of issue as the Flimbo's Quest) loader. I have attached a couple of .tap files, which I created using TLR's 
[Woolly_Jumper_S-Load.zip](https://github.com/GideonZ/1541ultimate/files/3635756/Woolly_Jumper_S-Load.zip)
S-Loader (Make S-Load) is an IRQ irq loader. The main boot loader fails to load on the U64, but both tap files work in VICE.  Perhaps by getting this loader to work, it could fix the problems with some other tape loaders!!?!?!?!?

**Comment by RichardTND** [comment]
... Quick update:

D64 original version of Flimbo seems to work. Tape version still fails, and blacks out instead of run loading picture. 
S-Load still doesn't work in latest U64 update

Problematic loaders perhaps!

**Comment by ikrananka** [comment]
I've been having a problem loading the original Ghostbusters Activision tape release and am wondering if this is the same/similar issue to Flimbo's Quest.  I've tried this with an original tape (**verified to work on a real PAL C64**) and also the .tap file attached which is from GameBase 64 v16.

[Ghostbusters.zip](https://github.com/GideonZ/1541ultimate/files/4767855/Ghostbusters.zip)

The game starts to load okay with the U64 showing the Activision splash screen, followed by the flashing coloured lines.  However, at the point the game should start, the screen fills with garbage characters and the U64 LED starts to flash.  My U64 details/settings are:

- Firmware : 1.28 (latest)
- C64 Type : PAL
- Cartridge = None

**Comment by RichardTND** [comment]
The .tap original works, which uses the Flash colour cycle load works but it has anti-disk drive protection. Go to the disk drive menu options and disable all disk drives and then re-load the .tap.

There have been some re-releases of this game, which all use an unprotected different tape loader

- Ricochet: Invade A Load
- Commodore Force Reel Action 22 - Novaload

**Comment by RichardTND** [comment]
I'm guessing it is the first tape released version you're trying to load and fail to run. I just gave it a go and managed to get the game to load. It is anti-disk drive protection that causes it garble up the screen and crash. Disable all drive activity (Edit disk drive settings to switch all drives off) then try and reload the tape image. Hopefully it should run.

Alternatively try the versions released on these as different tape loaders and protection doesn't exist:

- Ricohet/Mastertronic/Red Hot Hits : Invade-A-Load
- Big Box 30: Cult loader
- Commodore Force: Novaload

**Comment by ikrananka** [comment]
Thanks Richard, that was exactly the problem.  Huge thanks :)

I didn't have a disk drive back in the day so never came across this issue before.  I did try the other tape versions and they worked fine on the U64 even with the disk drives enabled.  But as you mentioned in an earlier edit they didn't use the disk drive copy protection that the original did.

Is there a good website(s) that lists all of the different copy protection/fast loaders and which games they were used on?

**Comment by RichardTND** [comment]
Cannot find any at the moment, but at least you'll know if you have trouble loading in a specific C64 game from tape and it doesn't run.

**Comment by ikrananka** [comment]
Indeed I will :)  I've also just realised, slow as I am on the uptake, that the "no 1541" in the TAP file name means exactly that - don't have an active 1541 connected when loading this tape.  I've lived and learned!!!

**Comment by GideonZ** [comment]
Flimbo's Quest is now loading correctly. Root cause: Read back of 6510 data register when direction register is set to output.
