### ISSUE TITLE
[U64 V1.20] Bad Apple doesn't render correctly

### ISSUE THREAD

**Issue by EgonOlsen71** [GideonZ/1541ultimate#96]
With the 1.20 firmware (and according to this (german) thread with every firmware after 1.10: [https://www.forum64.de/index.php?thread/84260-ultimate-64-boards-der-das-l%C3%A4uft-noch-nicht-thread/&postID=1394239#post1394239](https://www.forum64.de/index.php?thread/84260-ultimate-64-boards-der-das-l%C3%A4uft-noch-nicht-thread/&postID=1394239#post1394239)), the Bad Apple demo [(https://csdb.dk/release/?id=131628)](https://csdb.dk/release/?id=131628) doesn't render correctly around 50 secs. in the demo. Here's a video that shows the problem: [https://youtu.be/UmRGkq3fPZ8](https://youtu.be/UmRGkq3fPZ8) (skip to 0:55 to see the issue).

**Comment by Jumpman64** [comment]
Looks like this is related to the disk data streaming in this demo using alternate fastloader roms.
Bad Apple runs flawless with the original kernal and drive roms. 
These errors that occur after 0:52 seconds when Jiffy or SpeedDOS is enabled. Just changing one kernal to original didn't help. It seems both C64 and 1541 roms needs to be original.
I've tested it a few times on an U64 board v1.2 fw1.21/3.5a and Hoxs64.

**Comment by EgonOlsen71** [comment]
I'm not using any alternative roms. It's all original.

**Comment by marty41** [comment]
Maybe some more detail information could help. What revision of U64 mainboard are you using (1.1, 1.2)? If revision 1.1, did you apply the PLD 1.2 fix? Did you reset the configuration after updating to the new firmware (1.20)?
Does the "Bad Apple" demo run flawless on Jumpman64s U64?

**Comment by EgonOlsen71** [comment]
Mine is an early 1.2 board with the later patch for the CLPD applied to it. Config is default except for an added FPGASid, it has been reset after the update to 1.20 as well.

**Comment by Jumpman64** [comment]
First i've tried the Bad Apple Demo on my later U64 board v1.2 fw1.21/3.5a with SpeedDOS and Hoxs64 with Jiffy and they both showed the same picture errors after around 52 seconds of movie playtime when another part gets loaded.

Then i switched to the original ROMs and **it ran flawless several times**. :O

After Egon's remark i switchted ROMs back and forth and suddenly the errors showed up with the original ROMs too. 

Presumably it has something to do with the IRQ loading routine of the demo and the sensitive 1541 timing.

**Comment by Jumpman64** [comment]
@EgonOlsen71 Maybe you'll find some time to check the Bad Apple demo with the new fw 1.41 again? Looks like it's fixed. I ran the demo a couple of times now without any glitches. (Original, Jiffy, Dolphin, SpeedDOS)

**Comment by EgonOlsen71** [comment]
Seems to work fine now.
